"use client";

import { useState } from "react";
import type { PassageSideDetail, TextDiffResult, TextDiffSegment } from "@/lib/domain/passage";
import styles from "./PassageDiffView.module.css";

export interface PassageDiffViewProps {
  earlier: PassageSideDetail;
  later: PassageSideDetail;
  diff: TextDiffResult;
}

function renderSegments(segments: readonly TextDiffSegment[]) {
  return segments.map((segment, index) => {
    if (segment.op === "equal") return <span key={index}>{segment.text}</span>;
    if (segment.op === "delete") {
      return (
        <span key={index} className={styles.deleted}>
          {segment.text}
        </span>
      );
    }
    return (
      <span key={index} className={styles.inserted}>
        {segment.text}
      </span>
    );
  });
}

/**
 * Side-by-side (stacked on mobile via CSS grid) text-difference view for a
 * matched two-sided passage comparison. Presentation-only: `diff` never
 * feeds back into `alignmentStatus`/`confidence`/any analytical field --
 * see `buildTextDiff`. Defaults to the highlighted view; "Show original
 * text" swaps to the two complete, unhighlighted strings (still both fully
 * present, never truncated).
 */
export function PassageDiffView({ earlier, later, diff }: PassageDiffViewProps) {
  const [showOriginal, setShowOriginal] = useState(false);

  return (
    <div className={styles.wrapper}>
      <div className={styles.controls}>
        <button type="button" className={styles.toggle} onClick={() => setShowOriginal((value) => !value)} aria-pressed={showOriginal}>
          {showOriginal ? "Show highlighted differences" : "Show original text"}
        </button>
        {!diff.diffed && (
          <p className={styles.fallbackNote} role="note">
            This passage is too long for highlighted differencing -- showing the original text on both sides.
          </p>
        )}
      </div>
      <p className={styles.explainer} role="note">
        Highlighting is a visual reading aid generated by comparing the two published texts -- it is not the alignment
        algorithm itself and never changes the published alignment result.
      </p>

      <div className={styles.grid}>
        <div className={styles.column}>
          <h4 className={styles.columnHeading}>Earlier disclosure</h4>
          <p className={styles.text}>{showOriginal || !diff.diffed ? earlier.text : renderSegments(diff.earlier)}</p>
        </div>
        <div className={styles.column}>
          <h4 className={styles.columnHeading}>Later disclosure</h4>
          <p className={styles.text}>{showOriginal || !diff.diffed ? later.text : renderSegments(diff.later)}</p>
        </div>
      </div>
    </div>
  );
}
