"""Milestone 7A.1 application/publication schema.

Deliberately independent of the research `Base`
(`market_documents.db.base`): the app schema is a separate publication
target with its own Alembic history (`migrations_app/`), never mixed into
the research metadata, so migrating one database can never accidentally
touch the other's tables.

Every table's primary key is assigned explicitly by the publisher
(`publishing.labels.derive_id`) rather than generated by the database --
deterministic IDs are what make re-publishing the same `publication_version`
against unchanged source data idempotent (see `labels.py`).
"""

import enum
import uuid
from datetime import date, datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Computed,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class AppBase(DeclarativeBase):
    pass


class AppUUIDPkMixin:
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)


class AppCreatedAtMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class PublicationStatus(str, enum.Enum):
    PENDING = "PENDING"
    BUILDING = "BUILDING"
    VALIDATING = "VALIDATING"
    READY = "READY"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


_PUBLICATION_STATUS_VALUES = tuple(s.value for s in PublicationStatus)


# ---------------------------------------------------------------------------
# app_internal
# ---------------------------------------------------------------------------


class Publication(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One publish attempt. Never mutated in place after COMPLETED/FAILED
    except for `status`/`activated_at` transitions -- a build's row counts
    and validation summary are a permanent record of what was actually
    written."""

    __tablename__ = "publications"
    __table_args__ = (
        UniqueConstraint("publication_version", name="uq_publications_version"),
        CheckConstraint(
            "status IN " + str(_PUBLICATION_STATUS_VALUES), name="ck_publications_status"
        ),
        {"schema": "app_internal"},
    )

    publication_version: Mapped[str] = mapped_column(String(64), nullable=False)
    source_database_identifier: Mapped[str] = mapped_column(String(255), nullable=False)
    source_schema_version: Mapped[str] = mapped_column(String(64), nullable=False)
    source_configuration_hash: Mapped[str] = mapped_column(String(64), nullable=False)

    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default=PublicationStatus.PENDING.value
    )

    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    activated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    company_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    report_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    comparison_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    passage_comparison_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    language_metric_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    passage_language_signal_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    discovery_item_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    validation_summary: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    failure_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class ApplicationState(AppBase):
    """Singleton pointer at the currently-served publication. `app.current_*`
    views join to this row; see `schema.py` for the security implications of
    that join."""

    __tablename__ = "application_state"
    __table_args__ = ({"schema": "app_internal"},)

    singleton_key: Mapped[str] = mapped_column(String(16), primary_key=True, default="active")
    active_publication_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app_internal.publications.id"),
        nullable=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


# ---------------------------------------------------------------------------
# app
# ---------------------------------------------------------------------------


class Company(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "companies"
    __table_args__ = (
        UniqueConstraint("publication_id", "source_company_id", name="uq_app_companies_pub_source"),
        Index("ix_app_companies_publication_id", "publication_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_company_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)

    ticker: Mapped[str] = mapped_column(String(16), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    short_name: Mapped[str | None] = mapped_column(String(64), nullable=True)
    sector: Mapped[str | None] = mapped_column(String(128), nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    first_report_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    latest_report_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    report_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    comparison_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Not a foreign key: report_comparisons.company_id points back at this
    # table, so a DB-level FK here would be circular. Cross-referential
    # integrity between these two pointers and app.report_comparisons is
    # checked by `publishing.validation`, not the schema.
    latest_comparison_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    historical_peak_comparison_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    display_order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    has_current_data: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)


class Report(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "reports"
    __table_args__ = (
        UniqueConstraint("publication_id", "source_report_id", name="uq_app_reports_pub_source"),
        Index("ix_app_reports_publication_id", "publication_id"),
        Index("ix_app_reports_company_id", "company_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_report_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )

    title: Mapped[str] = mapped_column(String(512), nullable=False)
    filename: Mapped[str] = mapped_column(String(512), nullable=False)
    directory_year: Mapped[int] = mapped_column(Integer, nullable=False)
    period_start: Mapped[date | None] = mapped_column(Date, nullable=True)
    period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    narrative_word_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    extraction_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    extraction_quality_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    extraction_warning: Mapped[str | None] = mapped_column(Text, nullable=True)

    chronological_index: Mapped[int] = mapped_column(Integer, nullable=False)


class ReportComparison(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """The main application summary table -- one row per published report
    pair. Field groups follow the milestone brief exactly: identity/
    chronology, disclosure-change, report-side headline, passage-composition,
    quality (report-side and alignment-change kept independent, never
    blended), subdued technical fields, and deterministic findings."""

    __tablename__ = "report_comparisons"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "source_report_pair_id", name="uq_app_comparisons_pub_source"
        ),
        Index("ix_app_comparisons_publication_id", "publication_id"),
        Index("ix_app_comparisons_company_id", "company_id"),
        # Required for ON DELETE CASCADE from app.reports.
        Index("ix_app_comparisons_earlier_report_id", "earlier_report_id"),
        Index("ix_app_comparisons_later_report_id", "later_report_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_report_pair_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )
    earlier_report_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.reports.id", ondelete="CASCADE"), nullable=False
    )
    later_report_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.reports.id", ondelete="CASCADE"), nullable=False
    )
    earlier_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    later_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    gap_months: Mapped[int] = mapped_column(Integer, nullable=False)
    chronological_index: Mapped[int] = mapped_column(Integer, nullable=False)
    is_transition: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_irregular_gap: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_latest_for_company: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_historical_peak_change: Mapped[bool] = mapped_column(Boolean, nullable=False)

    disclosure_change_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    disclosure_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    disclosure_change_percentile: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Independent quality axis for the disclosure-change score specifically
    # -- distinct from `report_side_quality`/`alignment_change_quality`,
    # which are financial-language (Milestone 6) concepts. Added so a
    # NEEDS_REVIEW-quality score can still be displayed (with its quality
    # made explicit) rather than silently withheld -- see
    # `publisher._score_displayed`. `disclosure_change_quality` is the raw
    # upstream `FeatureQuality` value, never recalculated here.
    disclosure_change_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    disclosure_change_quality_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # Raw `ReportPairFeatures.primary_eligible`, verbatim -- never widened.
    # A review-qualified (NEEDS_REVIEW) score can be displayed with
    # `disclosure_change_primary_eligible=False`; that flag alone is what
    # keeps it out of primary discovery rankings (see `findings._gate_feature`).
    disclosure_change_primary_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    disclosure_change_warning: Mapped[str | None] = mapped_column(Text, nullable=True)

    net_tone_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    net_tone_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    uncertainty_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    uncertainty_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    risk_introduction_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_introduction_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    risk_removal_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_removal_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    governance_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    governance_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    financial_condition_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    financial_condition_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    forward_looking_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    forward_looking_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)

    new_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    removed_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    lightly_modified_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    substantially_modified_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ambiguous_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    report_side_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    report_side_quality_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    report_side_primary_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    report_side_warning: Mapped[str | None] = mapped_column(Text, nullable=True)

    alignment_change_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    alignment_change_quality_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    alignment_change_primary_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    alignment_change_warning: Mapped[str | None] = mapped_column(Text, nullable=True)

    dictionary_match_rate_earlier: Mapped[float | None] = mapped_column(Float, nullable=True)
    dictionary_match_rate_later: Mapped[float | None] = mapped_column(Float, nullable=True)
    ambiguous_word_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    collision_flagged_word_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    unmatched_word_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    structured_content_exclusion_share: Mapped[float | None] = mapped_column(Float, nullable=True)

    primary_finding_key: Mapped[str | None] = mapped_column(String(64), nullable=True)
    secondary_finding_key: Mapped[str | None] = mapped_column(String(64), nullable=True)
    tertiary_finding_key: Mapped[str | None] = mapped_column(String(64), nullable=True)
    finding_payload: Mapped[dict | None] = mapped_column(JSONB, nullable=True)


class LanguageMetric(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "language_metrics"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "report_comparison_id", "metric_scope", "population", "category", "subcategory",
            name="uq_app_language_metrics_scope",
        ),
        Index("ix_app_language_metrics_publication_id", "publication_id"),
        Index("ix_app_language_metrics_comparison_id", "report_comparison_id"),
        Index("ix_app_language_metrics_scope_category", "metric_scope", "category"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )

    metric_scope: Mapped[str] = mapped_column(String(32), nullable=False)
    population: Mapped[str] = mapped_column(String(64), nullable=False)
    category: Mapped[str] = mapped_column(String(64), nullable=False)
    subcategory: Mapped[str | None] = mapped_column(String(64), nullable=True)

    earlier_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    later_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    earlier_rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    later_rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    rate_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    absolute_rate_change: Mapped[float | None] = mapped_column(Float, nullable=True)

    introduced_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    introduced_rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    removed_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    removed_rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    retained_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    negated_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    primary_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)


class Passage(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "passages"
    __table_args__ = (
        UniqueConstraint("publication_id", "source_passage_id", name="uq_app_passages_pub_source"),
        Index("ix_app_passages_publication_id", "publication_id"),
        Index("ix_app_passages_report_id", "report_id"),
        Index("ix_app_passages_company_id", "company_id"),
        Index("ix_app_passages_search_vector", "search_vector", postgresql_using="gin"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_passage_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )
    report_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.reports.id", ondelete="CASCADE"), nullable=False
    )
    report_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    passage_index: Mapped[int] = mapped_column(Integer, nullable=False)
    first_page_number: Mapped[int] = mapped_column(Integer, nullable=False)
    last_page_number: Mapped[int] = mapped_column(Integer, nullable=False)
    heading: Mapped[str | None] = mapped_column(Text, nullable=True)
    passage_type: Mapped[str] = mapped_column(String(32), nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    word_count: Mapped[int] = mapped_column(Integer, nullable=False)

    # Recomputed fresh at publish time from `structured_content_audit.
    # classify_passage` -- the research `Passage` row has no stored category
    # column, so this is never a cached/stale value (see `source_dataset.py`).
    structured_content_category: Mapped[str | None] = mapped_column(String(64), nullable=True)
    primary_narrative_eligible: Mapped[bool] = mapped_column(Boolean, nullable=False)
    feature_eligible: Mapped[bool] = mapped_column(Boolean, nullable=False)

    # GENERATED ALWAYS ... STORED: the text-search config is a literal, so
    # this expression is IMMUTABLE and portable to any conventional Postgres
    # (12+) -- no trigger required.
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('pg_catalog.english', coalesce(heading, '')), 'A') || "
            "setweight(to_tsvector('pg_catalog.english', text), 'B')",
            persisted=True,
        ),
        nullable=True,
    )


class PassageComparison(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "passage_comparisons"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "source_alignment_id", name="uq_app_passage_comparisons_pub_source"
        ),
        Index("ix_app_passage_comparisons_publication_id", "publication_id"),
        Index("ix_app_passage_comparisons_report_comparison_id", "report_comparison_id"),
        # Required for ON DELETE CASCADE from app.passages -- without an
        # index on these FK columns, deleting a passage forces a sequential
        # scan of this entire table to find referencing rows.
        Index("ix_app_passage_comparisons_earlier_passage_id", "earlier_passage_id"),
        Index("ix_app_passage_comparisons_later_passage_id", "later_passage_id"),
        CheckConstraint(
            "earlier_passage_id IS NOT NULL OR later_passage_id IS NOT NULL",
            name="ck_app_passage_comparisons_one_side_present",
        ),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_alignment_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )
    earlier_passage_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passages.id", ondelete="CASCADE"), nullable=True
    )
    later_passage_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passages.id", ondelete="CASCADE"), nullable=True
    )

    alignment_status: Mapped[str] = mapped_column(String(32), nullable=False)
    alignment_type: Mapped[str] = mapped_column(String(32), nullable=False)
    confidence: Mapped[str] = mapped_column(String(32), nullable=False)
    confidence_label: Mapped[str] = mapped_column(String(64), nullable=False)

    semantic_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    lexical_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    heading_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    content_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    position_difference: Mapped[float | None] = mapped_column(Float, nullable=True)

    collision_flag: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    split_merge_flag: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    primary_alignment: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    review_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class PassageLanguageSignal(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One row per passage/category/subcategory combination -- a pivot of the
    research `PassageLanguageSignal`'s wide per-category columns (for the
    seven Loughran-McDonald categories) plus one row per non-zero
    `PassageLanguageCategoryHit` (custom taxonomy)."""

    __tablename__ = "passage_language_signals"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "passage_comparison_id", "report_side", "category", "subcategory",
            name="uq_app_passage_language_signals_scope",
        ),
        Index("ix_app_passage_language_signals_publication_id", "publication_id"),
        Index("ix_app_passage_language_signals_passage_id", "passage_id"),
        Index("ix_app_passage_language_signals_comparison_id", "report_comparison_id"),
        # Required for ON DELETE CASCADE from app.passage_comparisons -- see
        # the equivalent note on PassageComparison's earlier/later indexes.
        Index("ix_app_passage_language_signals_passage_comparison_id", "passage_comparison_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    passage_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passages.id", ondelete="CASCADE"), nullable=False
    )
    passage_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passage_comparisons.id", ondelete="CASCADE"), nullable=False
    )
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )
    report_side: Mapped[str] = mapped_column(String(16), nullable=False)
    category: Mapped[str] = mapped_column(String(64), nullable=False)
    subcategory: Mapped[str | None] = mapped_column(String(64), nullable=True)

    raw_count: Mapped[int] = mapped_column(Integer, nullable=False)
    negated_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    adjusted_count: Mapped[int] = mapped_column(Integer, nullable=False)
    rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)

    is_introduced: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_removed: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_retained: Mapped[bool] = mapped_column(Boolean, nullable=False)


class DiscoveryItem(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "discovery_items"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "discovery_type", "rank_scope", "report_comparison_id",
            name="uq_app_discovery_items_scope",
        ),
        Index("ix_app_discovery_items_publication_id", "publication_id"),
        Index("ix_app_discovery_items_company_id", "company_id"),
        Index("ix_app_discovery_items_type_scope_rank", "discovery_type", "rank_scope", "rank"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )

    discovery_type: Mapped[str] = mapped_column(String(64), nullable=False)
    rank_scope: Mapped[str] = mapped_column(String(32), nullable=False)
    score: Mapped[float] = mapped_column(Float, nullable=False)
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    percentile: Mapped[float | None] = mapped_column(Float, nullable=True)
    finding_key: Mapped[str] = mapped_column(String(64), nullable=False)
    supporting_metric_key: Mapped[str] = mapped_column(String(64), nullable=False)
    supporting_value: Mapped[float] = mapped_column(Float, nullable=False)
    supporting_unit: Mapped[str] = mapped_column(String(32), nullable=False)
    quality_label: Mapped[str] = mapped_column(String(64), nullable=False)


class MetricDefinition(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "metric_definitions"
    __table_args__ = (
        UniqueConstraint("publication_id", "metric_key", name="uq_app_metric_definitions_pub_key"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    metric_key: Mapped[str] = mapped_column(String(64), nullable=False)
    display_name: Mapped[str] = mapped_column(String(128), nullable=False)
    short_description: Mapped[str] = mapped_column(Text, nullable=False)
    technical_description: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str] = mapped_column(String(32), nullable=False)
    direction_interpretation: Mapped[str] = mapped_column(Text, nullable=False)
    methodology_anchor: Mapped[str] = mapped_column(String(255), nullable=False)


class MetricLabelThreshold(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "metric_label_thresholds"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "metric_key", "threshold_version", "label",
            name="uq_app_metric_label_thresholds_scope",
        ),
        Index("ix_app_metric_label_thresholds_metric_key", "metric_key"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    metric_key: Mapped[str] = mapped_column(String(64), nullable=False)
    threshold_version: Mapped[str] = mapped_column(String(32), nullable=False)
    label: Mapped[str] = mapped_column(String(64), nullable=False)
    minimum_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    maximum_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    display_order: Mapped[int] = mapped_column(Integer, nullable=False)
    explanation: Mapped[str] = mapped_column(Text, nullable=False)
