"""Milestone 7A.1 application/publication schema.

Deliberately independent of the research `Base`
(`market_documents.db.base`): the app schema is a separate publication
target with its own Alembic history (`migrations_app/`), never mixed into
the research metadata, so migrating one database can never accidentally
touch the other's tables.

Every table's primary key is assigned explicitly by the publisher
(`publishing.labels.derive_id`) rather than generated by the database --
deterministic IDs are what make re-publishing the same `publication_version`
against unchanged source data idempotent (see `labels.py`).
"""

import enum
import uuid
from datetime import date, datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Computed,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Fixed at the current source model's output size (BAAI/bge-small-en-v1.5,
# see `market_documents.services.embedding_config`). Deliberately not
# imported from the research package (the app schema stays independent of
# research modules) -- kept in sync by convention and by
# `publishing.validation`'s dimension check against the resolved source
# embedding at build time. A future model with a different dimension
# requires either a new migration changing this column, or a second
# versioned embedding table -- never a silent reinterpretation of existing
# vectors.
APP_EMBEDDING_DIMENSION = 384


class AppBase(DeclarativeBase):
    pass


class AppUUIDPkMixin:
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)


class AppCreatedAtMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class PublicationStatus(str, enum.Enum):
    PENDING = "PENDING"
    BUILDING = "BUILDING"
    VALIDATING = "VALIDATING"
    READY = "READY"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


_PUBLICATION_STATUS_VALUES = tuple(s.value for s in PublicationStatus)


# ---------------------------------------------------------------------------
# app_internal
# ---------------------------------------------------------------------------


class Publication(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One publish attempt. Never mutated in place after COMPLETED/FAILED
    except for `status`/`activated_at` transitions -- a build's row counts
    and validation summary are a permanent record of what was actually
    written."""

    __tablename__ = "publications"
    __table_args__ = (
        UniqueConstraint("publication_version", name="uq_publications_version"),
        CheckConstraint(
            "status IN " + str(_PUBLICATION_STATUS_VALUES), name="ck_publications_status"
        ),
        {"schema": "app_internal"},
    )

    publication_version: Mapped[str] = mapped_column(String(64), nullable=False)
    source_database_identifier: Mapped[str] = mapped_column(String(255), nullable=False)
    source_schema_version: Mapped[str] = mapped_column(String(64), nullable=False)
    source_configuration_hash: Mapped[str] = mapped_column(String(64), nullable=False)

    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default=PublicationStatus.PENDING.value
    )

    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    activated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    company_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    report_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    comparison_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    passage_comparison_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    language_metric_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    passage_language_signal_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    discovery_item_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Milestone 7B.2
    qa_chunk_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    qa_chunk_passage_mapping_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Milestone 7A.3/7A.4: Track 7C.6 cutover comparison rows
    narrative_comparison_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    structured_comparison_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    validation_summary: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    failure_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Track 7F.7a.5: which `app_artifacts.*` generation each shared family
    # resolves to for this publication. Nullable because a publication built
    # before this migration never wrote to `app_artifacts` at all -- its
    # rows carry their bulk content inline instead (see the `*_artifact_id`
    # columns on `PassageComparison`/`RetrievalContext`/`PassageLanguageSignal`/
    # `QaChunk` below). A reviewer can determine exactly which artifact
    # generations a publication depends on from these three columns alone,
    # without inspecting individual rows.
    alignment_artifact_version: Mapped[str | None] = mapped_column(String(64), nullable=True)
    language_signal_artifact_version: Mapped[str | None] = mapped_column(String(64), nullable=True)
    qa_chunking_artifact_version: Mapped[str | None] = mapped_column(String(64), nullable=True)


class ApplicationState(AppBase):
    """Singleton pointer at the currently-served publication. `app.current_*`
    views join to this row; see `schema.py` for the security implications of
    that join."""

    __tablename__ = "application_state"
    __table_args__ = ({"schema": "app_internal"},)

    singleton_key: Mapped[str] = mapped_column(String(16), primary_key=True, default="active")
    active_publication_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("app_internal.publications.id"),
        nullable=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


# ---------------------------------------------------------------------------
# app
# ---------------------------------------------------------------------------


class Company(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "companies"
    __table_args__ = (
        UniqueConstraint("publication_id", "source_company_id", name="uq_app_companies_pub_source"),
        Index("ix_app_companies_publication_id", "publication_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_company_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)

    ticker: Mapped[str] = mapped_column(String(16), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    short_name: Mapped[str | None] = mapped_column(String(64), nullable=True)
    sector: Mapped[str | None] = mapped_column(String(128), nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    first_report_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    latest_report_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    report_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    comparison_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Not a foreign key: report_comparisons.company_id points back at this
    # table, so a DB-level FK here would be circular. Cross-referential
    # integrity between these two pointers and app.report_comparisons is
    # checked by `publishing.validation`, not the schema.
    latest_comparison_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    historical_peak_comparison_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    display_order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    has_current_data: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)


class Report(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "reports"
    __table_args__ = (
        UniqueConstraint("publication_id", "source_report_id", name="uq_app_reports_pub_source"),
        Index("ix_app_reports_publication_id", "publication_id"),
        Index("ix_app_reports_company_id", "company_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_report_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )

    title: Mapped[str] = mapped_column(String(512), nullable=False)
    filename: Mapped[str] = mapped_column(String(512), nullable=False)
    directory_year: Mapped[int] = mapped_column(Integer, nullable=False)
    period_start: Mapped[date | None] = mapped_column(Date, nullable=True)
    period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    narrative_word_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    extraction_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    extraction_quality_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    extraction_warning: Mapped[str | None] = mapped_column(Text, nullable=True)

    chronological_index: Mapped[int] = mapped_column(Integer, nullable=False)


class ReportComparison(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """The main application summary table -- one row per published report
    pair. Field groups follow the milestone brief exactly: identity/
    chronology, disclosure-change, report-side headline, passage-composition,
    quality (report-side and alignment-change kept independent, never
    blended), subdued technical fields, and deterministic findings."""

    __tablename__ = "report_comparisons"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "source_report_pair_id", name="uq_app_comparisons_pub_source"
        ),
        Index("ix_app_comparisons_publication_id", "publication_id"),
        Index("ix_app_comparisons_company_id", "company_id"),
        # Required for ON DELETE CASCADE from app.reports.
        Index("ix_app_comparisons_earlier_report_id", "earlier_report_id"),
        Index("ix_app_comparisons_later_report_id", "later_report_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_report_pair_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )
    earlier_report_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.reports.id", ondelete="CASCADE"), nullable=False
    )
    later_report_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.reports.id", ondelete="CASCADE"), nullable=False
    )
    earlier_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    later_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    gap_months: Mapped[int] = mapped_column(Integer, nullable=False)
    chronological_index: Mapped[int] = mapped_column(Integer, nullable=False)
    is_transition: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_irregular_gap: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_latest_for_company: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_historical_peak_change: Mapped[bool] = mapped_column(Boolean, nullable=False)

    disclosure_change_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    disclosure_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    disclosure_change_percentile: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Independent quality axis for the disclosure-change score specifically
    # -- distinct from `report_side_quality`/`alignment_change_quality`,
    # which are financial-language (Milestone 6) concepts. Added so a
    # NEEDS_REVIEW-quality score can still be displayed (with its quality
    # made explicit) rather than silently withheld -- see
    # `publisher._score_displayed`. `disclosure_change_quality` is the raw
    # upstream `FeatureQuality` value, never recalculated here.
    disclosure_change_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    disclosure_change_quality_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # Raw `ReportPairFeatures.primary_eligible`, verbatim -- never widened.
    # A review-qualified (NEEDS_REVIEW) score can be displayed with
    # `disclosure_change_primary_eligible=False`; that flag alone is what
    # keeps it out of primary discovery rankings (see `findings._gate_feature`).
    disclosure_change_primary_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    disclosure_change_warning: Mapped[str | None] = mapped_column(Text, nullable=True)

    net_tone_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    net_tone_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    uncertainty_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    uncertainty_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    risk_introduction_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_introduction_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    risk_removal_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_removal_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    governance_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    governance_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    financial_condition_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    financial_condition_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # Track 7F.4: M3 (financial_condition_share_change) is the Discover
    # ranking/materiality metric; M6b (financial_condition_topic_mix_change)
    # is supporting detail only, never labeled (no positive/negative
    # direction). `financial_condition_change` above (M1) is unchanged,
    # retained as descriptive context -- never repurposed.
    financial_condition_share_earlier: Mapped[float | None] = mapped_column(Float, nullable=True)
    financial_condition_share_later: Mapped[float | None] = mapped_column(Float, nullable=True)
    financial_condition_share_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    financial_condition_share_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    financial_condition_topic_mix_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Track 7F.7a.1: M3-G (governance_share_change) is the Discover
    # ranking/materiality metric; M6-G (governance_topic_mix_change) is
    # supporting detail only, never labeled (no positive/negative
    # direction). `governance_change` above (M1-G) is unchanged, retained
    # as descriptive context -- never repurposed. Exact mirror of the
    # financial_condition M3/M6b block above.
    governance_share_earlier: Mapped[float | None] = mapped_column(Float, nullable=True)
    governance_share_later: Mapped[float | None] = mapped_column(Float, nullable=True)
    governance_share_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    governance_share_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    governance_topic_mix_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Track 7F.7a.1a: raw counts behind M3-G's share ratio, so the
    # comparison/evidence UI can state the factual count/share decomposition
    # for a governance finding instead of the removed |M1-G| < 1.0
    # heuristic. See `ReportPairLanguageFeatures.governance_hits_earlier`.
    governance_hits_earlier: Mapped[int | None] = mapped_column(Integer, nullable=True)
    governance_hits_later: Mapped[int | None] = mapped_column(Integer, nullable=True)
    custom_taxonomy_hits_earlier: Mapped[int | None] = mapped_column(Integer, nullable=True)
    custom_taxonomy_hits_later: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Track 7F.9: unified Discover topic-change metric (C_min) plus its legs,
    # inputs, and supporting-only alignment-unit diagnostics, published
    # verbatim from `ReportPairLanguageFeatures` (see that model and
    # docs/discover-metrics-unified-implementation-7f9.md). The density leg
    # M1 is the existing `financial_condition_change`/`governance_change`/
    # `uncertainty_change` column; `uncertainty_hits_*` mirrors the research
    # `uncertainty_count_*` columns under the topic-metric naming.
    feature_eligible_primary_words_earlier: Mapped[int | None] = mapped_column(Integer, nullable=True)
    feature_eligible_primary_words_later: Mapped[int | None] = mapped_column(Integer, nullable=True)
    financial_condition_hits_earlier: Mapped[int | None] = mapped_column(Integer, nullable=True)
    financial_condition_hits_later: Mapped[int | None] = mapped_column(Integer, nullable=True)
    uncertainty_hits_earlier: Mapped[int | None] = mapped_column(Integer, nullable=True)
    uncertainty_hits_later: Mapped[int | None] = mapped_column(Integer, nullable=True)
    financial_condition_count_change_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    governance_count_change_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    uncertainty_count_change_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    financial_condition_topic_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    governance_topic_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    uncertainty_topic_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    financial_condition_supporting_hits: Mapped[int | None] = mapped_column(Integer, nullable=True)
    financial_condition_opposing_hits: Mapped[int | None] = mapped_column(Integer, nullable=True)
    financial_condition_change_consistency_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    financial_condition_largest_passage_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    governance_supporting_hits: Mapped[int | None] = mapped_column(Integer, nullable=True)
    governance_opposing_hits: Mapped[int | None] = mapped_column(Integer, nullable=True)
    governance_change_consistency_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    governance_largest_passage_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    uncertainty_supporting_hits: Mapped[int | None] = mapped_column(Integer, nullable=True)
    uncertainty_opposing_hits: Mapped[int | None] = mapped_column(Integer, nullable=True)
    uncertainty_change_consistency_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    uncertainty_largest_passage_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Track 7F.9: net-tone components (`net_tone_change = positive_rate_
    # change - negative_rate_change`), so "net tone decline" can say whether
    # it came from fewer positive words or more negative words.
    positive_rate_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    negative_rate_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    forward_looking_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    forward_looking_change_label: Mapped[str | None] = mapped_column(String(64), nullable=True)

    new_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    removed_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    lightly_modified_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    substantially_modified_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ambiguous_passage_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    report_side_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    report_side_quality_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    report_side_primary_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    report_side_warning: Mapped[str | None] = mapped_column(Text, nullable=True)

    alignment_change_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    alignment_change_quality_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    alignment_change_primary_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    alignment_change_warning: Mapped[str | None] = mapped_column(Text, nullable=True)

    dictionary_match_rate_earlier: Mapped[float | None] = mapped_column(Float, nullable=True)
    dictionary_match_rate_later: Mapped[float | None] = mapped_column(Float, nullable=True)
    ambiguous_word_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    collision_flagged_word_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    unmatched_word_share: Mapped[float | None] = mapped_column(Float, nullable=True)
    structured_content_exclusion_share: Mapped[float | None] = mapped_column(Float, nullable=True)

    primary_finding_key: Mapped[str | None] = mapped_column(String(64), nullable=True)
    secondary_finding_key: Mapped[str | None] = mapped_column(String(64), nullable=True)
    tertiary_finding_key: Mapped[str | None] = mapped_column(String(64), nullable=True)
    finding_payload: Mapped[dict | None] = mapped_column(JSONB, nullable=True)


class LanguageMetric(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "language_metrics"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "report_comparison_id", "metric_scope", "population", "category", "subcategory",
            name="uq_app_language_metrics_scope",
        ),
        Index("ix_app_language_metrics_publication_id", "publication_id"),
        Index("ix_app_language_metrics_comparison_id", "report_comparison_id"),
        Index("ix_app_language_metrics_scope_category", "metric_scope", "category"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )

    metric_scope: Mapped[str] = mapped_column(String(32), nullable=False)
    population: Mapped[str] = mapped_column(String(64), nullable=False)
    category: Mapped[str] = mapped_column(String(64), nullable=False)
    subcategory: Mapped[str | None] = mapped_column(String(64), nullable=True)

    earlier_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    later_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    earlier_rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    later_rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    rate_change: Mapped[float | None] = mapped_column(Float, nullable=True)
    absolute_rate_change: Mapped[float | None] = mapped_column(Float, nullable=True)

    introduced_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    introduced_rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    removed_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    removed_rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)
    retained_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    negated_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    primary_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)


class Passage(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "passages"
    __table_args__ = (
        UniqueConstraint("publication_id", "source_passage_id", name="uq_app_passages_pub_source"),
        Index("ix_app_passages_publication_id", "publication_id"),
        Index("ix_app_passages_report_id", "report_id"),
        Index("ix_app_passages_company_id", "company_id"),
        Index("ix_app_passages_search_vector", "search_vector", postgresql_using="gin"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_passage_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )
    report_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.reports.id", ondelete="CASCADE"), nullable=False
    )
    report_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    passage_index: Mapped[int] = mapped_column(Integer, nullable=False)
    first_page_number: Mapped[int] = mapped_column(Integer, nullable=False)
    last_page_number: Mapped[int] = mapped_column(Integer, nullable=False)
    heading: Mapped[str | None] = mapped_column(Text, nullable=True)
    passage_type: Mapped[str] = mapped_column(String(32), nullable=False)
    # Track 7E.1: nullable as of migration app_0010. A passage's `text` is a
    # byte-for-byte copy of stable research content (verified: 100% identical
    # across publications of unchanged source data -- see docs/7e1-
    # publication-storage-lifecycle-hardening.md) and is now stored ONCE per
    # `source_passage_id` in `app_corpus.passages`, never duplicated per
    # publication. The publisher leaves this column NULL for every publish
    # from app_0010 onward; `app.current_passages` resolves the real text via
    # a join to `app_corpus.passages` on `source_passage_id`. Rows written by
    # publications built before app_0010 keep their historical populated
    # value (non-destructive migration -- never backfilled to NULL).
    text: Mapped[str | None] = mapped_column(Text, nullable=True)
    word_count: Mapped[int] = mapped_column(Integer, nullable=False)

    # Recomputed fresh at publish time from `structured_content_audit.
    # classify_passage` -- the research `Passage` row has no stored category
    # column, so this is never a cached/stale value (see `source_dataset.py`).
    structured_content_category: Mapped[str | None] = mapped_column(String(64), nullable=True)
    primary_narrative_eligible: Mapped[bool] = mapped_column(Boolean, nullable=False)
    feature_eligible: Mapped[bool] = mapped_column(Boolean, nullable=False)

    # GENERATED ALWAYS ... STORED: the text-search config is a literal, so
    # this expression is IMMUTABLE and portable to any conventional Postgres
    # (12+) -- no trigger required.
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('pg_catalog.english', coalesce(heading, '')), 'A') || "
            "setweight(to_tsvector('pg_catalog.english', text), 'B')",
            persisted=True,
        ),
        nullable=True,
    )


class PassageComparison(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "passage_comparisons"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "source_alignment_id", name="uq_app_passage_comparisons_pub_source"
        ),
        Index("ix_app_passage_comparisons_publication_id", "publication_id"),
        Index("ix_app_passage_comparisons_report_comparison_id", "report_comparison_id"),
        # Required for ON DELETE CASCADE from app.passages -- without an
        # index on these FK columns, deleting a passage forces a sequential
        # scan of this entire table to find referencing rows.
        Index("ix_app_passage_comparisons_earlier_passage_id", "earlier_passage_id"),
        Index("ix_app_passage_comparisons_later_passage_id", "later_passage_id"),
        CheckConstraint(
            "earlier_passage_id IS NOT NULL OR later_passage_id IS NOT NULL",
            name="ck_app_passage_comparisons_one_side_present",
        ),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    source_alignment_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )
    earlier_passage_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passages.id", ondelete="CASCADE"), nullable=True
    )
    later_passage_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passages.id", ondelete="CASCADE"), nullable=True
    )
    # Track 7F.7a.5: added by migration app_0014. NULL from that migration
    # onward -- the publisher no longer populates this row's own content
    # columns below (also relaxed to nullable by the same migration);
    # `app.current_passage_comparisons` resolves them via COALESCE against
    # `app_artifacts.passage_comparisons` instead. A publication built
    # before app_0014 keeps this NULL and its own content columns populated
    # (COALESCE prefers them), exactly the `Passage.text`/`app_corpus`
    # precedent from Track 7E.1.
    alignment_artifact_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.passage_comparisons.id"), nullable=True
    )

    alignment_status: Mapped[str | None] = mapped_column(String(32), nullable=True)
    alignment_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    confidence: Mapped[str | None] = mapped_column(String(32), nullable=True)
    confidence_label: Mapped[str | None] = mapped_column(String(64), nullable=True)

    semantic_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    lexical_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    heading_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    content_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    position_difference: Mapped[float | None] = mapped_column(Float, nullable=True)

    collision_flag: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    split_merge_flag: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    primary_alignment: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    review_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class NarrativeUnitComparison(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """Track 7C.6 semantic-unit comparison, persisted at publish time for
    every report-comparison whose (ticker, schedule, unit_key) is in the
    fixed `cutover_config.NEW_PIPELINE_NARRATIVE_SCOPE` scope -- always
    computed with the cutover router force-enabled (mirroring
    `compare-cutover --force-enabled`), regardless of the live
    `SEMANTIC_COMPARISON_CUTOVER_ENABLED` flag at publish time. Whether the
    live caller actually *prefers* this row over the legacy
    `ReportComparison` fields is a read-time decision made by the web
    application against its own copy of that flag -- see
    docs/7a3-7a4-live-comparison-integration.md. `status` may be
    `UNRESOLVED_UPSTREAM`/`AMBIGUOUS`/`REVIEW_REQUIRED`: an unresolved row is
    still published (never silently substituted with a legacy result), so
    the caller can render an explicit unresolved state."""

    __tablename__ = "narrative_unit_comparisons"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "report_comparison_id", "unit_key",
            name="uq_app_narrative_unit_comparisons_scope",
        ),
        Index("ix_app_narrative_unit_comparisons_publication_id", "publication_id"),
        Index("ix_app_narrative_unit_comparisons_comparison_id", "report_comparison_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )

    schedule: Mapped[str] = mapped_column(String(64), nullable=False)
    unit_key: Mapped[str] = mapped_column(String(128), nullable=False)

    comparison_backend: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)

    alignment_status: Mapped[str | None] = mapped_column(String(32), nullable=True)
    alignment_confidence: Mapped[str | None] = mapped_column(String(32), nullable=True)
    analytical_mode: Mapped[str | None] = mapped_column(String(32), nullable=True)

    lexical_metrics: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    earlier_word_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    later_word_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    earlier_provenance: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    later_provenance: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    review_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class StructuredTableComparison(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """Track 7C.6 structured-table comparison, persisted at publish time for
    every report-comparison whose (ticker, table_family_key) is in the fixed
    `cutover_config.NEW_PIPELINE_STRUCTURED_SCOPE` scope. One report
    comparison may have more than one row (ACT has two in-scope table
    families). Row/column alignments, value-change events, and footnotes are
    stored as JSONB arrays rather than normalized child tables: only two
    table families are in scope for this integration milestone, so a fully
    normalized shape would be schema sprawl this milestone does not need
    (docs/7a3-7a4-live-comparison-integration.md). Same publish-time/
    read-time flag split as `NarrativeUnitComparison` above."""

    __tablename__ = "structured_table_comparisons"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "report_comparison_id", "table_family_key",
            name="uq_app_structured_table_comparisons_scope",
        ),
        Index("ix_app_structured_table_comparisons_publication_id", "publication_id"),
        Index("ix_app_structured_table_comparisons_comparison_id", "report_comparison_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )

    table_family_key: Mapped[str] = mapped_column(String(128), nullable=False)

    comparison_backend: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)

    row_alignments: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    column_alignments: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    value_change_events: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    footnotes: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    earlier_provenance: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    later_provenance: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    review_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class PassageLanguageSignal(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One row per passage/category/subcategory combination with a non-zero
    count -- a sparse pivot of the research `PassageLanguageSignal`'s wide
    per-category columns (for the seven Loughran-McDonald categories) plus
    one row per non-zero `PassageLanguageCategoryHit` (custom taxonomy).
    Zero-count categories are not materialized."""

    __tablename__ = "passage_language_signals"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "passage_comparison_id", "report_side", "category", "subcategory",
            name="uq_app_passage_language_signals_scope",
        ),
        Index("ix_app_passage_language_signals_publication_id", "publication_id"),
        Index("ix_app_passage_language_signals_passage_id", "passage_id"),
        Index("ix_app_passage_language_signals_comparison_id", "report_comparison_id"),
        # Required for ON DELETE CASCADE from app.passage_comparisons -- see
        # the equivalent note on PassageComparison's earlier/later indexes.
        Index("ix_app_passage_language_signals_passage_comparison_id", "passage_comparison_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    passage_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passages.id", ondelete="CASCADE"), nullable=False
    )
    passage_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passage_comparisons.id", ondelete="CASCADE"), nullable=False
    )
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )
    report_side: Mapped[str] = mapped_column(String(16), nullable=False)
    category: Mapped[str] = mapped_column(String(64), nullable=False)
    subcategory: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # Track 7F.7a.5: added by migration app_0014 -- same NULL-until-resolved-
    # by-COALESCE-view pattern as `PassageComparison.alignment_artifact_id`.
    language_signal_artifact_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.passage_language_signals.id"), nullable=True
    )

    raw_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    negated_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    adjusted_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)

    is_introduced: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    is_removed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    is_retained: Mapped[bool | None] = mapped_column(Boolean, nullable=True)


class DiscoveryItem(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "discovery_items"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "discovery_type", "rank_scope", "report_comparison_id",
            name="uq_app_discovery_items_scope",
        ),
        Index("ix_app_discovery_items_publication_id", "publication_id"),
        Index("ix_app_discovery_items_company_id", "company_id"),
        Index("ix_app_discovery_items_type_scope_rank", "discovery_type", "rank_scope", "rank"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )
    report_comparison_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=False
    )

    discovery_type: Mapped[str] = mapped_column(String(64), nullable=False)
    rank_scope: Mapped[str] = mapped_column(String(32), nullable=False)
    score: Mapped[float] = mapped_column(Float, nullable=False)
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    percentile: Mapped[float | None] = mapped_column(Float, nullable=True)
    finding_key: Mapped[str] = mapped_column(String(64), nullable=False)
    supporting_metric_key: Mapped[str] = mapped_column(String(64), nullable=False)
    supporting_value: Mapped[float] = mapped_column(Float, nullable=False)
    supporting_unit: Mapped[str] = mapped_column(String(32), nullable=False)
    quality_label: Mapped[str] = mapped_column(String(64), nullable=False)


class MetricDefinition(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "metric_definitions"
    __table_args__ = (
        UniqueConstraint("publication_id", "metric_key", name="uq_app_metric_definitions_pub_key"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    metric_key: Mapped[str] = mapped_column(String(64), nullable=False)
    display_name: Mapped[str] = mapped_column(String(128), nullable=False)
    short_description: Mapped[str] = mapped_column(Text, nullable=False)
    technical_description: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str] = mapped_column(String(32), nullable=False)
    direction_interpretation: Mapped[str] = mapped_column(Text, nullable=False)
    methodology_anchor: Mapped[str] = mapped_column(String(255), nullable=False)


class MetricLabelThreshold(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    __tablename__ = "metric_label_thresholds"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "metric_key", "threshold_version", "label",
            name="uq_app_metric_label_thresholds_scope",
        ),
        Index("ix_app_metric_label_thresholds_metric_key", "metric_key"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    metric_key: Mapped[str] = mapped_column(String(64), nullable=False)
    threshold_version: Mapped[str] = mapped_column(String(32), nullable=False)
    label: Mapped[str] = mapped_column(String(64), nullable=False)
    minimum_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    maximum_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    display_order: Mapped[int] = mapped_column(Integer, nullable=False)
    explanation: Mapped[str] = mapped_column(Text, nullable=False)


# ---------------------------------------------------------------------------
# Milestone 7B.1: comparison-aware semantic retrieval (Option C)
# ---------------------------------------------------------------------------


class PassageEmbedding(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One deduplicated vector per published passage -- never one per
    retrieval context. A passage that participates in two passage
    comparisons still has exactly one row here; `RetrievalContext` is what
    fans a single vector out into its valid comparison-specific
    interpretations (see module docstring notes in `publisher.py`)."""

    __tablename__ = "passage_embeddings"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "passage_id", "embedding_model", "embedding_model_revision",
            name="uq_app_passage_embeddings_scope",
        ),
        Index("ix_app_passage_embeddings_publication_id", "publication_id"),
        Index("ix_app_passage_embeddings_passage_id", "passage_id"),
        Index(
            "ix_app_passage_embeddings_hnsw_cosine",
            "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    passage_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passages.id", ondelete="CASCADE"), nullable=False
    )

    # Research-side lineage -- traceable but never queried live from here;
    # the research database is never reachable from the application layer.
    source_embedding_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    source_embedding_run_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)

    embedding_model: Mapped[str] = mapped_column(String(255), nullable=False)
    embedding_model_revision: Mapped[str] = mapped_column(String(64), nullable=False)
    dimensions: Mapped[int] = mapped_column(Integer, nullable=False)
    # sha256 of the exact `app.passages.text` this vector was computed from.
    # The research side has no equivalent hash (see docstring in
    # `publishing.retrieval_contexts`) -- this is a forward-looking drift
    # detector, not a cross-checked value at publish time.
    embedding_text_hash: Mapped[str] = mapped_column(String(64), nullable=False)

    embedding: Mapped[list[float]] = mapped_column(Vector(APP_EMBEDDING_DIMENSION), nullable=False)
    vector_norm: Mapped[float] = mapped_column(Float, nullable=False)


class RetrievalContext(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One analytical interpretation of one passage: either linked to a
    specific passage-comparison side, or (rarely) a `REPORT_ONLY` context
    for a passage that never participates in any published comparison.

    Deliberately keyed so a passage can have more than one row here (one per
    valid comparison side it occupies) while `PassageEmbedding` stays
    deduplicated at the passage level -- see the Option C architecture note
    in `publisher.py`.
    """

    __tablename__ = "retrieval_contexts"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "passage_id", "passage_comparison_id", "report_side", "context_type",
            name="uq_app_retrieval_contexts_scope",
            postgresql_nulls_not_distinct=True,
        ),
        Index("ix_app_retrieval_contexts_publication_id", "publication_id"),
        Index("ix_app_retrieval_contexts_passage_id", "passage_id"),
        Index("ix_app_retrieval_contexts_passage_embedding_id", "passage_embedding_id"),
        Index("ix_app_retrieval_contexts_passage_comparison_id", "passage_comparison_id"),
        Index("ix_app_retrieval_contexts_report_comparison_id", "report_comparison_id"),
        Index("ix_app_retrieval_contexts_report_id", "report_id"),
        Index("ix_app_retrieval_contexts_company_id", "company_id"),
        CheckConstraint(
            "context_type IN ('COMPARISON_LINKED', 'REPORT_ONLY')",
            name="ck_app_retrieval_contexts_context_type",
        ),
        CheckConstraint(
            "(context_type = 'COMPARISON_LINKED' AND passage_comparison_id IS NOT NULL "
            "AND report_comparison_id IS NOT NULL AND report_side IS NOT NULL) "
            "OR (context_type = 'REPORT_ONLY' AND passage_comparison_id IS NULL "
            "AND report_comparison_id IS NULL AND report_side IS NULL)",
            name="ck_app_retrieval_contexts_type_consistency",
        ),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    passage_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passages.id", ondelete="CASCADE"), nullable=False
    )
    # Track 7E.1: DB-level FK dropped by migration app_0010 -- not a foreign
    # key any more. A publication built before app_0010 still holds a value
    # pointing at a per-publication `app.passage_embeddings.id` row; a
    # publication built from app_0010 onward holds a value pointing at the
    # shared `app_corpus.passage_embeddings.id` row instead (never
    # duplicated per publication -- see that table's docstring). A single FK
    # constraint cannot target two different tables, so cross-referential
    # integrity here is checked by `publishing.validation`, not the schema --
    # the same pattern already used for `Company.latest_comparison_id`
    # above. Critically, this also means deleting a superseded publication
    # (which cascades away that publication's OWN `retrieval_contexts` rows
    # via `publication_id`, unaffected by this change) can never cascade
    # into deleting a shared `app_corpus.passage_embeddings` row that
    # another, still-live publication references -- see section 7 of
    # docs/7e1-publication-storage-lifecycle-hardening.md.
    passage_embedding_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    passage_comparison_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passage_comparisons.id", ondelete="CASCADE"), nullable=True
    )
    report_comparison_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.report_comparisons.id", ondelete="CASCADE"), nullable=True
    )
    report_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.reports.id", ondelete="CASCADE"), nullable=False
    )
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )

    # Track 7F.7a.5: added by migration app_0014 -- same NULL-until-resolved-
    # by-COALESCE-view pattern as `PassageComparison.alignment_artifact_id`.
    # Deliberately the SAME `ALIGNMENT_ARTIFACT_VERSION` axis as
    # `PassageComparison` (see `labels.py`) rather than a separate one --
    # retrieval-context content is derived entirely from alignment/passage-
    # comparison inputs and has never needed its own version axis.
    alignment_artifact_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.retrieval_contexts.id"), nullable=True
    )

    context_type: Mapped[str] = mapped_column(String(32), nullable=False)
    report_side: Mapped[str | None] = mapped_column(String(16), nullable=True)
    alignment_status: Mapped[str | None] = mapped_column(String(32), nullable=True)
    alignment_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    confidence: Mapped[str | None] = mapped_column(String(32), nullable=True)

    report_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    earlier_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    later_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)

    heading: Mapped[str | None] = mapped_column(Text, nullable=True)
    passage_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    primary_narrative_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    feature_eligible: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    structured_content_category: Mapped[str | None] = mapped_column(String(64), nullable=True)

    report_side_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)
    alignment_change_quality: Mapped[str | None] = mapped_column(String(32), nullable=True)

    collision_flag: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    split_merge_flag: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    irregular_gap_flag: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)


class RetrievalContextLanguageCategory(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """Distinct financial-language categories with at least one non-zero
    signal for this context's (passage_comparison_id, report_side) scope --
    normalized rather than JSONB/array so the frontend can filter/index by
    category the same way it already does against `passage_language_signals`."""

    __tablename__ = "retrieval_context_language_categories"
    __table_args__ = (
        UniqueConstraint(
            "retrieval_context_id", "category", name="uq_app_rc_language_categories_scope"
        ),
        Index("ix_app_rc_language_categories_publication_id", "publication_id"),
        Index("ix_app_rc_language_categories_context_id", "retrieval_context_id"),
        Index("ix_app_rc_language_categories_category", "category"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    retrieval_context_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.retrieval_contexts.id", ondelete="CASCADE"), nullable=False
    )
    # Track 7F.7a.5: added by migration app_0014, purely for GC/reuse
    # provenance -- `category` itself stays populated directly on this thin
    # row (never nulled, no COALESCE view rewrite here): a single short
    # string is already minimal, so there is no meaningful byte saving in
    # resolving it through `app_artifacts` at read time. This link only lets
    # the reuse/GC mechanism be exercised at this table's granularity too.
    retrieval_context_artifact_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.retrieval_context_language_categories.id"), nullable=True
    )
    category: Mapped[str] = mapped_column(String(64), nullable=False)


class RetrievalContextRiskSubcategory(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """Distinct risk subcategories (category='risk') with at least one
    non-zero signal for this context's scope."""

    __tablename__ = "retrieval_context_risk_subcategories"
    __table_args__ = (
        UniqueConstraint(
            "retrieval_context_id", "subcategory", name="uq_app_rc_risk_subcategories_scope"
        ),
        Index("ix_app_rc_risk_subcategories_publication_id", "publication_id"),
        Index("ix_app_rc_risk_subcategories_context_id", "retrieval_context_id"),
        Index("ix_app_rc_risk_subcategories_subcategory", "subcategory"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    retrieval_context_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.retrieval_contexts.id", ondelete="CASCADE"), nullable=False
    )
    # Track 7F.7a.5: same GC/reuse-provenance-only link as
    # `RetrievalContextLanguageCategory.retrieval_context_artifact_id` above.
    retrieval_context_artifact_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.retrieval_context_risk_subcategories.id"), nullable=True
    )
    subcategory: Mapped[str] = mapped_column(String(64), nullable=False)


# ---------------------------------------------------------------------------
# Milestone 7B.2: standard-RAG Q&A retrieval chunks
# ---------------------------------------------------------------------------
#
# A second, additive vector representation alongside `PassageEmbedding` --
# never a replacement. `PassageEmbedding` stays the citation/comparison
# identity (one deduplicated vector per passage); `QaChunk` exists purely to
# improve retrieval recall for free-text questions, built from overlapping
# ~350-token windows over a report's passages (see `publishing.qa_chunking`).
# A `QaChunk` is never a citation object on its own -- `/ask` always resolves
# final citations back through `QaChunkPassage` to real `app.passages`
# rows, report pages, and (transitively) comparisons, exactly like the
# 7B.1d `qa_experiment` spike's parent-mapping discipline, but against a
# real, published, `app_readonly`-servable table.


class QaChunk(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One overlapping ~350-token retrieval chunk, one embedding each.
    Deduplicated within a report by `embedding_text_hash` at build time
    (see `publisher.py`) -- two windows that happen to produce byte-identical
    text collapse to one row via the deterministic id, never two."""

    __tablename__ = "qa_chunks"
    __table_args__ = (
        UniqueConstraint(
            "publication_id", "report_id", "chunk_index", name="uq_app_qa_chunks_pub_report_index"
        ),
        Index("ix_app_qa_chunks_publication_id", "publication_id"),
        Index("ix_app_qa_chunks_report_id", "report_id"),
        Index("ix_app_qa_chunks_company_id", "company_id"),
        # Track 7F.10: lets the artifact-first QA vector search (HNSW scan
        # on `app_artifacts.qa_chunks`, see `postgres-qa-chunk-repository.
        # ts`) resolve each candidate to the active publication's thin row
        # by nested-loop index lookup, preserving the HNSW ordering.
        Index("ix_app_qa_chunks_artifact_publication", "qa_chunking_artifact_id", "publication_id"),
        Index(
            "ix_app_qa_chunks_hnsw_cosine",
            "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        CheckConstraint("page_start <= page_end", name="ck_app_qa_chunks_page_range"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    report_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.reports.id", ondelete="CASCADE"), nullable=False
    )
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.companies.id", ondelete="CASCADE"), nullable=False
    )

    # Track 7F.7a.5: added by migration app_0014 -- same NULL-until-resolved-
    # by-COALESCE-view pattern as `PassageComparison.alignment_artifact_id`.
    # Combines `labels.QA_CHUNKING_ARTIFACT_VERSION` with `embedding_model`/
    # `embedding_model_revision` in its identity (see `ArtifactQaChunk` in
    # this module) since chunk *embeddings* additionally depend on the model.
    qa_chunking_artifact_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.qa_chunks.id"), nullable=True
    )

    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    text: Mapped[str | None] = mapped_column(Text, nullable=True)
    section_heading: Mapped[str | None] = mapped_column(Text, nullable=True)
    page_start: Mapped[int | None] = mapped_column(Integer, nullable=True)
    page_end: Mapped[int | None] = mapped_column(Integer, nullable=True)
    token_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    truncation_policy: Mapped[str | None] = mapped_column(String(32), nullable=True)

    embedding_model: Mapped[str | None] = mapped_column(String(255), nullable=True)
    embedding_model_revision: Mapped[str | None] = mapped_column(String(64), nullable=True)
    dimensions: Mapped[int | None] = mapped_column(Integer, nullable=True)
    embedding_text_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    embedding: Mapped[list[float] | None] = mapped_column(Vector(APP_EMBEDDING_DIMENSION), nullable=True)
    vector_norm: Mapped[float | None] = mapped_column(Float, nullable=True)

    # GENERATED ALWAYS ... STORED: same pattern as `Passage.search_vector`,
    # enabling optional lexical retrieval over chunk text (brief: "optional
    # lexical retrieval over Q&A chunk text").
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('pg_catalog.english', coalesce(section_heading, '')), 'A') || "
            "setweight(to_tsvector('pg_catalog.english', text), 'B')",
            persisted=True,
        ),
        nullable=True,
    )


class QaChunkPassage(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """Many-to-many mapping of a chunk to every canonical `app.passages` row
    its character span overlaps -- the parent-resolution table `/ask`
    citations resolve through to reach a real, stable passage identity."""

    __tablename__ = "qa_chunk_passages"
    __table_args__ = (
        UniqueConstraint("qa_chunk_id", "passage_id", name="uq_app_qa_chunk_passages_scope"),
        Index("ix_app_qa_chunk_passages_publication_id", "publication_id"),
        Index("ix_app_qa_chunk_passages_qa_chunk_id", "qa_chunk_id"),
        Index("ix_app_qa_chunk_passages_passage_id", "passage_id"),
        {"schema": "app"},
    )

    publication_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_internal.publications.id", ondelete="CASCADE"), nullable=False
    )
    qa_chunk_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.qa_chunks.id", ondelete="CASCADE"), nullable=False
    )
    passage_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app.passages.id", ondelete="CASCADE"), nullable=False
    )
    # Track 7F.7a.5: same GC/reuse-provenance-only link as
    # `RetrievalContextLanguageCategory.retrieval_context_artifact_id` --
    # `member_order` is a single small integer, not worth a COALESCE view.
    qa_chunk_passage_artifact_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.qa_chunk_passages.id"), nullable=True
    )
    member_order: Mapped[int] = mapped_column(Integer, nullable=False)


# ---------------------------------------------------------------------------
# Track 7E.1: shared, publication-independent corpus (app_corpus schema)
# ---------------------------------------------------------------------------
#
# Everything above this line is scoped by `publication_id` and physically
# duplicated per publication by design (see each table's docstring). The two
# tables below are deliberately NOT publication-scoped: they hold the two
# heaviest artifacts the publisher writes (passage text, passage embedding
# vectors), both of which are pure, byte-for-byte-verified copies of stable
# research-side content (docs/7e1-publication-storage-lifecycle-hardening.md
# section 2) -- never a function of `publication_version`. One row exists per
# distinct `source_passage_id` (and, for embeddings, per distinct embedding
# model/revision too), no matter how many publications reference it.
#
# Rows here are immutable once written (never UPDATEd by the publisher) and
# are never CASCADE-deleted by a publication going away -- deleting a
# `Publication` only ever cascades its own `app.*` rows (see each table's own
# note). A row becomes eligible for removal only once no `app.passages`/
# `app.retrieval_contexts` row anywhere still references it; see
# `publisher.gc_orphaned_corpus_rows`.
#
# IDs are derived via `labels.derive_corpus_id`, which fixes `publication_
# version` to the reserved `labels.CORPUS_SCOPE` sentinel instead of a real
# publication's version string -- this is what makes the id (and therefore
# whether a publish INSERTs a new row or reuses an existing one) a pure
# function of source identity, deliberately never of which publication is
# being built.


class CorpusPassage(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """The narrative text of one research passage, stored exactly once
    regardless of how many publications include that passage. `app.passages`
    (per-publication) keeps its own `heading`/`word_count`/page numbers/
    `passage_type` -- small, and legitimately re-derived per publish -- but
    leaves `text` NULL from migration app_0010 onward and resolves it here
    via `app.current_passages` (a join on `source_passage_id`, benchmarked
    locally at ~1ms warm-cache overhead against the semantic-search hot path
    -- see docs/7e1-publication-storage-lifecycle-hardening.md section 9)."""

    __tablename__ = "passages"
    __table_args__ = (
        UniqueConstraint("source_passage_id", name="uq_app_corpus_passages_source"),
        Index("ix_app_corpus_passages_search_vector", "search_vector", postgresql_using="gin"),
        {"schema": "app_corpus"},
    )

    source_passage_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    # Carried alongside `text` purely so the generated `search_vector` below
    # reproduces the exact same weighted formula `app.passages.search_vector`
    # used before app_0010 -- not the authoritative heading (that stays on
    # `app.passages`, which may legitimately differ in future if a
    # publication ever re-derives heading text independent of the corpus).
    heading: Mapped[str | None] = mapped_column(Text, nullable=True)
    text: Mapped[str] = mapped_column(Text, nullable=False)

    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('pg_catalog.english', coalesce(heading, '')), 'A') || "
            "setweight(to_tsvector('pg_catalog.english', text), 'B')",
            persisted=True,
        ),
        nullable=True,
    )


class CorpusPassageEmbedding(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One embedding vector per `(source_passage_id, embedding_model,
    embedding_model_revision)`, stored exactly once regardless of how many
    publications reference it. Replaces per-publication `app.
    passage_embeddings` rows for every publish from migration app_0010
    onward -- the publisher no longer writes to `app.passage_embeddings` at
    all; `RetrievalContext.passage_embedding_id` points directly at a row
    here instead (see that column's docstring). The single HNSW index below
    covers every distinct vector ever computed, never duplicated per
    publication -- smaller and faster to build than N per-publication
    copies of the same index."""

    __tablename__ = "passage_embeddings"
    __table_args__ = (
        UniqueConstraint(
            "source_passage_id", "embedding_model", "embedding_model_revision",
            name="uq_app_corpus_passage_embeddings_scope",
        ),
        Index(
            "ix_app_corpus_passage_embeddings_hnsw_cosine",
            "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        {"schema": "app_corpus"},
    )

    source_passage_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)

    # Research-side lineage -- same meaning as the legacy per-publication
    # column of the same name (never queried live from here; the research
    # database is never reachable from the application layer).
    source_embedding_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    source_embedding_run_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)

    embedding_model: Mapped[str] = mapped_column(String(255), nullable=False)
    embedding_model_revision: Mapped[str] = mapped_column(String(64), nullable=False)
    dimensions: Mapped[int] = mapped_column(Integer, nullable=False)
    embedding_text_hash: Mapped[str] = mapped_column(String(64), nullable=False)

    embedding: Mapped[list[float]] = mapped_column(Vector(APP_EMBEDDING_DIMENSION), nullable=False)
    vector_norm: Mapped[float] = mapped_column(Float, nullable=False)


# ---------------------------------------------------------------------------
# Track 7F.7a.5: versioned shared artifacts (`app_artifacts` schema)
# ---------------------------------------------------------------------------
#
# Same shape as `app_corpus.*` above -- NOT scoped by `publication_id`, IDs
# assigned via `labels.derive_id` (never a fresh per-family sentinel like
# `CORPUS_SCOPE`: each family passes its own real, bumpable version constant
# from `labels.py` instead) -- but keyed by a per-family *version*, not a
# fixed one, so a release that only changes one family's generation logic
# creates a new generation for that family alone, leaving the other three
# families' existing rows/generations untouched and still shared by every
# publication that references them. See docs/versioned-shared-artifacts-
# implementation-7f7a5.md for the full design and
# `publisher.py`'s existence-check-before-insert construction sites for how
# a build decides whether to reuse an existing generation or create one.
#
# `content_hash` on the four large tables is a defensive check only (see
# `labels.py`'s version-bump-rules docstring and section 8 of the design
# doc): the version key is the sole identity mechanism used for reuse
# lookups; the hash exists purely so a build that computes different
# content under the SAME identity+version (a developer changed generation
# logic without bumping the version) fails loudly instead of silently
# reusing or overwriting the row -- see `publisher._check_content_hash`.


class ArtifactPassageComparison(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One passage-comparison's alignment/scoring payload, shared across
    every publication whose alignment logic (and therefore
    `labels.ALIGNMENT_ARTIFACT_VERSION`) is unchanged for this
    `source_alignment_id`. `earlier_source_passage_id`/
    `later_source_passage_id` are research-side passage identities (the same
    key space as `app_corpus.passages.source_passage_id`), never a
    publication's own `app.passages.id` -- a single artifact generation must
    resolve identically no matter which publication references it, and two
    different publications assign two different ids to the same source
    passage (see `app.passages.id`'s derivation in `publisher.py`)."""

    __tablename__ = "passage_comparisons"
    __table_args__ = (
        UniqueConstraint(
            "source_alignment_id", "alignment_artifact_version",
            name="uq_app_artifacts_passage_comparisons_source_version",
        ),
        Index("ix_app_artifacts_passage_comparisons_source", "source_alignment_id"),
        {"schema": "app_artifacts"},
    )

    source_alignment_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    alignment_artifact_version: Mapped[str] = mapped_column(String(64), nullable=False)

    earlier_source_passage_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    later_source_passage_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    alignment_status: Mapped[str] = mapped_column(String(32), nullable=False)
    alignment_type: Mapped[str] = mapped_column(String(32), nullable=False)
    confidence: Mapped[str] = mapped_column(String(32), nullable=False)
    confidence_label: Mapped[str] = mapped_column(String(64), nullable=False)

    semantic_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    lexical_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    heading_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    content_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    position_difference: Mapped[float | None] = mapped_column(Float, nullable=True)

    collision_flag: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    split_merge_flag: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    primary_alignment: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    review_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)


class ArtifactRetrievalContext(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One retrieval-context's classification payload, shared across every
    publication whose alignment logic is unchanged for this `source_key`
    (the comparison-linked side's `source_alignment_id`, or the report-only
    passage's `source_passage_id`, as text -- a single column rather than
    two nullable UUID columns since the two cases never share a namespace
    and never need independently-typed lookups)."""

    __tablename__ = "retrieval_contexts"
    __table_args__ = (
        UniqueConstraint(
            "source_key", "report_side", "context_type", "alignment_artifact_version",
            name="uq_app_artifacts_retrieval_contexts_scope",
            postgresql_nulls_not_distinct=True,
        ),
        Index("ix_app_artifacts_retrieval_contexts_source_key", "source_key"),
        {"schema": "app_artifacts"},
    )

    source_key: Mapped[str] = mapped_column(String(64), nullable=False)
    report_side: Mapped[str | None] = mapped_column(String(16), nullable=True)
    context_type: Mapped[str] = mapped_column(String(32), nullable=False)
    alignment_artifact_version: Mapped[str] = mapped_column(String(64), nullable=False)

    source_passage_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)

    alignment_status: Mapped[str | None] = mapped_column(String(32), nullable=True)
    alignment_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    confidence: Mapped[str | None] = mapped_column(String(32), nullable=True)
    heading: Mapped[str | None] = mapped_column(Text, nullable=True)
    passage_type: Mapped[str] = mapped_column(String(32), nullable=False)
    primary_narrative_eligible: Mapped[bool] = mapped_column(Boolean, nullable=False)
    feature_eligible: Mapped[bool] = mapped_column(Boolean, nullable=False)
    structured_content_category: Mapped[str | None] = mapped_column(String(64), nullable=True)
    collision_flag: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    split_merge_flag: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)


class ArtifactRetrievalContextLanguageCategory(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """GC/reuse-provenance counterpart of `RetrievalContextLanguageCategory`
    -- see that thin model's `retrieval_context_artifact_id` docstring for
    why its `category` value is never resolved through this table at read
    time."""

    __tablename__ = "retrieval_context_language_categories"
    __table_args__ = (
        UniqueConstraint(
            "retrieval_context_artifact_id", "category",
            name="uq_app_artifacts_rc_language_categories_scope",
        ),
        {"schema": "app_artifacts"},
    )

    retrieval_context_artifact_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.retrieval_contexts.id", ondelete="CASCADE"), nullable=False
    )
    category: Mapped[str] = mapped_column(String(64), nullable=False)


class ArtifactRetrievalContextRiskSubcategory(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """GC/reuse-provenance counterpart of `RetrievalContextRiskSubcategory`
    -- same rationale as `ArtifactRetrievalContextLanguageCategory` above."""

    __tablename__ = "retrieval_context_risk_subcategories"
    __table_args__ = (
        UniqueConstraint(
            "retrieval_context_artifact_id", "subcategory",
            name="uq_app_artifacts_rc_risk_subcategories_scope",
        ),
        {"schema": "app_artifacts"},
    )

    retrieval_context_artifact_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.retrieval_contexts.id", ondelete="CASCADE"), nullable=False
    )
    subcategory: Mapped[str] = mapped_column(String(64), nullable=False)


class ArtifactPassageLanguageSignal(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One passage/category/subcategory language-signal count, shared across
    every publication whose signal-extraction logic (and therefore
    `labels.LANGUAGE_SIGNAL_ARTIFACT_VERSION`) is unchanged.

    Track 7F.10: identity is (`source_passage_alignment_id`, `report_side`,
    `category`, `subcategory`, version) from signals_v2 onward -- a research
    alignment row is stable across every `LanguageSignalRun` pinned to the
    same `AlignmentRun`, unlike the research `PassageLanguageSignal.id` each
    run mints afresh. signals_v1 rows (app_0014/app_0015 builds) keep their
    original `source_signal_id` identity and NULL alignment id; the two
    partial unique indexes below each cover exactly one scheme, and
    `ck_..._identity` guarantees every row carries one of them."""

    __tablename__ = "passage_language_signals"
    __table_args__ = (
        Index(
            "uq_app_artifacts_passage_language_signals_scope",
            "source_signal_id", "report_side", "category", "subcategory", "language_signal_artifact_version",
            unique=True,
            postgresql_nulls_not_distinct=True,
            postgresql_where=text("source_signal_id IS NOT NULL"),
        ),
        Index(
            "uq_app_artifacts_passage_language_signals_alignment_scope",
            "source_passage_alignment_id", "report_side", "category", "subcategory",
            "language_signal_artifact_version",
            unique=True,
            postgresql_nulls_not_distinct=True,
            postgresql_where=text("source_passage_alignment_id IS NOT NULL"),
        ),
        CheckConstraint(
            "source_signal_id IS NOT NULL OR source_passage_alignment_id IS NOT NULL",
            name="ck_app_artifacts_passage_language_signals_identity",
        ),
        Index("ix_app_artifacts_passage_language_signals_source", "source_signal_id"),
        {"schema": "app_artifacts"},
    )

    # signals_v1 identity only (NULL from signals_v2 onward).
    source_signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    # signals_v2+ identity (NULL on signals_v1 rows). `source_passage_id` is
    # lineage, determined by (alignment, side) -- also folded into the
    # content hash as a defensive check.
    source_passage_alignment_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    source_passage_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    report_side: Mapped[str] = mapped_column(String(16), nullable=False)
    category: Mapped[str] = mapped_column(String(64), nullable=False)
    subcategory: Mapped[str | None] = mapped_column(String(64), nullable=True)
    language_signal_artifact_version: Mapped[str] = mapped_column(String(64), nullable=False)

    raw_count: Mapped[int] = mapped_column(Integer, nullable=False)
    negated_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    adjusted_count: Mapped[int] = mapped_column(Integer, nullable=False)
    rate_per_1000: Mapped[float | None] = mapped_column(Float, nullable=True)

    is_introduced: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_removed: Mapped[bool] = mapped_column(Boolean, nullable=False)
    is_retained: Mapped[bool] = mapped_column(Boolean, nullable=False)

    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)


class ArtifactQaChunk(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """One QA retrieval chunk, shared across every publication built from
    unchanged source data with the same `labels.QA_CHUNKING_ARTIFACT_VERSION`
    AND the same `embedding_model`/`embedding_model_revision` -- chunk
    *embeddings* depend on the model even when the chunk-window builder
    itself hasn't changed, so both must match for reuse (see `labels.py`'s
    version-bump-rules docstring)."""

    __tablename__ = "qa_chunks"
    __table_args__ = (
        UniqueConstraint(
            "source_report_id", "chunk_index", "qa_chunking_artifact_version",
            "embedding_model", "embedding_model_revision",
            name="uq_app_artifacts_qa_chunks_scope",
        ),
        Index("ix_app_artifacts_qa_chunks_source_report_id", "source_report_id"),
        Index(
            "ix_app_artifacts_qa_chunks_hnsw_cosine",
            "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
        CheckConstraint("page_start <= page_end", name="ck_app_artifacts_qa_chunks_page_range"),
        {"schema": "app_artifacts"},
    )

    source_report_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    qa_chunking_artifact_version: Mapped[str] = mapped_column(String(64), nullable=False)

    text: Mapped[str] = mapped_column(Text, nullable=False)
    section_heading: Mapped[str | None] = mapped_column(Text, nullable=True)
    page_start: Mapped[int] = mapped_column(Integer, nullable=False)
    page_end: Mapped[int] = mapped_column(Integer, nullable=False)
    token_count: Mapped[int] = mapped_column(Integer, nullable=False)
    truncation_policy: Mapped[str] = mapped_column(String(32), nullable=False, default="none")

    embedding_model: Mapped[str] = mapped_column(String(255), nullable=False)
    embedding_model_revision: Mapped[str] = mapped_column(String(64), nullable=False)
    dimensions: Mapped[int] = mapped_column(Integer, nullable=False)
    embedding_text_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    embedding: Mapped[list[float]] = mapped_column(Vector(APP_EMBEDDING_DIMENSION), nullable=False)
    vector_norm: Mapped[float] = mapped_column(Float, nullable=False)

    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('pg_catalog.english', coalesce(section_heading, '')), 'A') || "
            "setweight(to_tsvector('pg_catalog.english', text), 'B')",
            persisted=True,
        ),
        nullable=True,
    )

    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)


class ArtifactQaChunkPassage(AppUUIDPkMixin, AppCreatedAtMixin, AppBase):
    """GC/reuse-provenance counterpart of `QaChunkPassage` -- `member_order`
    is never resolved through this table at read time (same rationale as
    `ArtifactRetrievalContextLanguageCategory`)."""

    __tablename__ = "qa_chunk_passages"
    __table_args__ = (
        UniqueConstraint(
            "qa_chunk_artifact_id", "source_member_passage_id",
            name="uq_app_artifacts_qa_chunk_passages_scope",
        ),
        {"schema": "app_artifacts"},
    )

    qa_chunk_artifact_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("app_artifacts.qa_chunks.id", ondelete="CASCADE"), nullable=False
    )
    source_member_passage_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    member_order: Mapped[int] = mapped_column(Integer, nullable=False)
