"""Deterministic report-level narrative assembly.

The narrative text is always regenerated by reading persisted Page/
TextBlock rows for one extraction run -- page order, then reading order
within a page, skipping anything flagged `excluded_from_narrative`. It is
never treated as an independent source of truth; if it were lost it could
be rebuilt from the stored blocks alone.
"""

import hashlib
import uuid

from sqlalchemy import select
from sqlalchemy.orm import Session

from market_documents.models.extraction import ExtractionRun, NarrativeDocument, Page


def build_narrative_text(session: Session, extraction_run_id: uuid.UUID) -> str:
    pages = session.scalars(
        select(Page)
        .where(Page.extraction_run_id == extraction_run_id)
        .order_by(Page.page_number)
    ).all()

    paragraphs: list[str] = []
    for page in pages:
        kept_blocks = sorted(
            (block for block in page.text_blocks if not block.excluded_from_narrative),
            key=lambda block: block.reading_order,
        )
        for block in kept_blocks:
            content = (block.cleaned_text or block.raw_text).strip()
            if content:
                paragraphs.append(content)

    return "\n\n".join(paragraphs)


def compute_content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def build_narrative_document(session: Session, extraction_run: ExtractionRun) -> NarrativeDocument:
    """Build and stage (but do not commit) a NarrativeDocument for a run."""
    text = build_narrative_text(session, extraction_run.id)
    document = NarrativeDocument(
        extraction_run_id=extraction_run.id,
        report_id=extraction_run.report_id,
        cleaned_text=text,
        word_count=len(text.split()),
        content_hash=compute_content_hash(text),
    )
    session.add(document)
    return document
