"""financial language signals

Revision ID: 21524e40a375
Revises: f3a7c9d21b6e
Create Date: 2026-07-27 10:28:15.131433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21524e40a375'
down_revision: Union[str, Sequence[str], None] = 'f3a7c9d21b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_language_dictionaries',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('license_notes', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('term_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_financial_language_dictionaries_name_version')
    )
    op.create_table('financial_language_terms',
    sa.Column('dictionary_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('normalized_term', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('polarity', sa.String(length=16), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_phrase', sa.Boolean(), nullable=False),
    sa.Column('phrase_token_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['financial_language_dictionaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dictionary_id', 'normalized_term', 'category', name='uq_financial_language_terms_dict_term_category')
    )
    op.create_index('ix_financial_language_terms_category', 'financial_language_terms', ['category'], unique=False)
    op.create_index('ix_financial_language_terms_dictionary_id', 'financial_language_terms', ['dictionary_id'], unique=False)
    op.create_index('ix_financial_language_terms_normalized_term', 'financial_language_terms', ['normalized_term'], unique=False)
    op.create_table('language_signal_runs',
    sa.Column('report_pair_id', sa.UUID(), nullable=False),
    sa.Column('feature_run_id', sa.UUID(), nullable=False),
    sa.Column('alignment_run_id', sa.UUID(), nullable=False),
    sa.Column('dictionary_id', sa.UUID(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('signal_version', sa.String(length=64), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='language_signal_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alignment_run_id'], ['alignment_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dictionary_id'], ['financial_language_dictionaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_run_id'], ['feature_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_pair_id'], ['report_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_language_signal_runs_pair_completed_at', 'language_signal_runs', ['report_pair_id', 'completed_at'], unique=False)
    op.create_index('ix_language_signal_runs_pair_status', 'language_signal_runs', ['report_pair_id', 'status'], unique=False)
    op.create_table('passage_language_signals',
    sa.Column('language_signal_run_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('passage_alignment_id', sa.UUID(), nullable=False),
    sa.Column('report_side', sa.Enum('EARLIER', 'LATER', name='report_side'), nullable=False),
    sa.Column('alignment_status', postgresql.ENUM('UNCHANGED', 'LIGHTLY_MODIFIED', 'SUBSTANTIALLY_MODIFIED', 'NEW', 'REMOVED', 'AMBIGUOUS', name='alignment_status', create_type=False), nullable=False),
    sa.Column('confidence', postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', 'NEEDS_REVIEW', name='alignment_confidence', create_type=False), nullable=False),
    sa.Column('passage_type', postgresql.ENUM('HEADING_WITH_BODY', 'PARAGRAPH', 'MULTI_PARAGRAPH', 'LIST', 'TABLE_CONTEXT', 'OTHER', name='passage_type', create_type=False), nullable=False),
    sa.Column('passage_word_count', sa.Integer(), nullable=False),
    sa.Column('structured_content_category', sa.String(length=64), nullable=True),
    sa.Column('primary_narrative_eligible', sa.Boolean(), nullable=False),
    sa.Column('feature_eligible', sa.Boolean(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('uncertainty_count', sa.Integer(), nullable=False),
    sa.Column('litigious_count', sa.Integer(), nullable=False),
    sa.Column('constraining_count', sa.Integer(), nullable=False),
    sa.Column('strong_modal_count', sa.Integer(), nullable=False),
    sa.Column('weak_modal_count', sa.Integer(), nullable=False),
    sa.Column('negated_hit_count', sa.Integer(), nullable=False),
    sa.Column('total_dictionary_hits', sa.Integer(), nullable=False),
    sa.Column('category_hit_count', sa.Integer(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_signal_run_id'], ['language_signal_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_alignment_id'], ['passage_alignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_signal_run_id', 'passage_alignment_id', 'report_side', name='uq_passage_language_signals_run_alignment_side')
    )
    op.create_index('ix_passage_language_signals_alignment_status', 'passage_language_signals', ['language_signal_run_id', 'alignment_status'], unique=False)
    op.create_index('ix_passage_language_signals_passage_id', 'passage_language_signals', ['passage_id'], unique=False)
    op.create_index('ix_passage_language_signals_run_id', 'passage_language_signals', ['language_signal_run_id'], unique=False)
    op.create_table('report_pair_language_features',
    sa.Column('language_signal_run_id', sa.UUID(), nullable=False),
    sa.Column('report_pair_id', sa.UUID(), nullable=False),
    sa.Column('earlier_report_id', sa.UUID(), nullable=False),
    sa.Column('later_report_id', sa.UUID(), nullable=False),
    sa.Column('all_passages_earlier_count', sa.Integer(), nullable=False),
    sa.Column('all_passages_later_count', sa.Integer(), nullable=False),
    sa.Column('all_passages_earlier_words', sa.Integer(), nullable=False),
    sa.Column('all_passages_later_words', sa.Integer(), nullable=False),
    sa.Column('primary_narrative_earlier_count', sa.Integer(), nullable=False),
    sa.Column('primary_narrative_later_count', sa.Integer(), nullable=False),
    sa.Column('primary_narrative_earlier_words', sa.Float(), nullable=False),
    sa.Column('primary_narrative_later_words', sa.Float(), nullable=False),
    sa.Column('excluded_structured_content_count', sa.Integer(), nullable=False),
    sa.Column('excluded_structured_content_words', sa.Float(), nullable=False),
    sa.Column('list_content_count', sa.Integer(), nullable=False),
    sa.Column('list_content_words', sa.Float(), nullable=False),
    sa.Column('table_context_count', sa.Integer(), nullable=False),
    sa.Column('table_context_words', sa.Float(), nullable=False),
    sa.Column('currency_exposure_mixed_count', sa.Integer(), nullable=False),
    sa.Column('currency_exposure_mixed_words', sa.Float(), nullable=False),
    sa.Column('uncertain_count', sa.Integer(), nullable=False),
    sa.Column('uncertain_words', sa.Float(), nullable=False),
    sa.Column('primary_narrative_words_excluding_lists', sa.Float(), nullable=False),
    sa.Column('primary_narrative_words_excluding_table_context', sa.Float(), nullable=False),
    sa.Column('primary_narrative_words_excluding_currency_exposure_mixed', sa.Float(), nullable=False),
    sa.Column('primary_narrative_words_excluding_uncertain', sa.Float(), nullable=False),
    sa.Column('positive_count_earlier', sa.Integer(), nullable=False),
    sa.Column('positive_count_later', sa.Integer(), nullable=False),
    sa.Column('positive_rate_earlier', sa.Float(), nullable=True),
    sa.Column('positive_rate_later', sa.Float(), nullable=True),
    sa.Column('positive_rate_change', sa.Float(), nullable=True),
    sa.Column('positive_rate_change_abs', sa.Float(), nullable=True),
    sa.Column('negative_count_earlier', sa.Integer(), nullable=False),
    sa.Column('negative_count_later', sa.Integer(), nullable=False),
    sa.Column('negative_rate_earlier', sa.Float(), nullable=True),
    sa.Column('negative_rate_later', sa.Float(), nullable=True),
    sa.Column('negative_rate_change', sa.Float(), nullable=True),
    sa.Column('negative_rate_change_abs', sa.Float(), nullable=True),
    sa.Column('uncertainty_count_earlier', sa.Integer(), nullable=False),
    sa.Column('uncertainty_count_later', sa.Integer(), nullable=False),
    sa.Column('uncertainty_rate_earlier', sa.Float(), nullable=True),
    sa.Column('uncertainty_rate_later', sa.Float(), nullable=True),
    sa.Column('uncertainty_rate_change', sa.Float(), nullable=True),
    sa.Column('uncertainty_rate_change_abs', sa.Float(), nullable=True),
    sa.Column('litigious_count_earlier', sa.Integer(), nullable=False),
    sa.Column('litigious_count_later', sa.Integer(), nullable=False),
    sa.Column('litigious_rate_earlier', sa.Float(), nullable=True),
    sa.Column('litigious_rate_later', sa.Float(), nullable=True),
    sa.Column('litigious_rate_change', sa.Float(), nullable=True),
    sa.Column('litigious_rate_change_abs', sa.Float(), nullable=True),
    sa.Column('constraining_count_earlier', sa.Integer(), nullable=False),
    sa.Column('constraining_count_later', sa.Integer(), nullable=False),
    sa.Column('constraining_rate_earlier', sa.Float(), nullable=True),
    sa.Column('constraining_rate_later', sa.Float(), nullable=True),
    sa.Column('constraining_rate_change', sa.Float(), nullable=True),
    sa.Column('constraining_rate_change_abs', sa.Float(), nullable=True),
    sa.Column('strong_modal_count_earlier', sa.Integer(), nullable=False),
    sa.Column('strong_modal_count_later', sa.Integer(), nullable=False),
    sa.Column('strong_modal_rate_earlier', sa.Float(), nullable=True),
    sa.Column('strong_modal_rate_later', sa.Float(), nullable=True),
    sa.Column('strong_modal_rate_change', sa.Float(), nullable=True),
    sa.Column('strong_modal_rate_change_abs', sa.Float(), nullable=True),
    sa.Column('weak_modal_count_earlier', sa.Integer(), nullable=False),
    sa.Column('weak_modal_count_later', sa.Integer(), nullable=False),
    sa.Column('weak_modal_rate_earlier', sa.Float(), nullable=True),
    sa.Column('weak_modal_rate_later', sa.Float(), nullable=True),
    sa.Column('weak_modal_rate_change', sa.Float(), nullable=True),
    sa.Column('weak_modal_rate_change_abs', sa.Float(), nullable=True),
    sa.Column('positive_hits_new', sa.Integer(), nullable=False),
    sa.Column('positive_hits_removed', sa.Integer(), nullable=False),
    sa.Column('positive_hits_ambiguous', sa.Integer(), nullable=False),
    sa.Column('negative_hits_new', sa.Integer(), nullable=False),
    sa.Column('negative_hits_removed', sa.Integer(), nullable=False),
    sa.Column('negative_hits_ambiguous', sa.Integer(), nullable=False),
    sa.Column('uncertainty_hits_new', sa.Integer(), nullable=False),
    sa.Column('uncertainty_hits_removed', sa.Integer(), nullable=False),
    sa.Column('uncertainty_hits_ambiguous', sa.Integer(), nullable=False),
    sa.Column('litigious_hits_new', sa.Integer(), nullable=False),
    sa.Column('litigious_hits_removed', sa.Integer(), nullable=False),
    sa.Column('litigious_hits_ambiguous', sa.Integer(), nullable=False),
    sa.Column('constraining_hits_new', sa.Integer(), nullable=False),
    sa.Column('constraining_hits_removed', sa.Integer(), nullable=False),
    sa.Column('constraining_hits_ambiguous', sa.Integer(), nullable=False),
    sa.Column('strong_modal_hits_new', sa.Integer(), nullable=False),
    sa.Column('strong_modal_hits_removed', sa.Integer(), nullable=False),
    sa.Column('strong_modal_hits_ambiguous', sa.Integer(), nullable=False),
    sa.Column('weak_modal_hits_new', sa.Integer(), nullable=False),
    sa.Column('weak_modal_hits_removed', sa.Integer(), nullable=False),
    sa.Column('weak_modal_hits_ambiguous', sa.Integer(), nullable=False),
    sa.Column('substantially_modified_positive_rate_change', sa.Float(), nullable=True),
    sa.Column('substantially_modified_negative_rate_change', sa.Float(), nullable=True),
    sa.Column('substantially_modified_uncertainty_rate_change', sa.Float(), nullable=True),
    sa.Column('high_confidence_dictionary_hits', sa.Integer(), nullable=False),
    sa.Column('high_and_medium_confidence_dictionary_hits', sa.Integer(), nullable=False),
    sa.Column('net_tone_earlier', sa.Float(), nullable=True),
    sa.Column('net_tone_later', sa.Float(), nullable=True),
    sa.Column('net_tone_change', sa.Float(), nullable=True),
    sa.Column('uncertainty_intensity_change', sa.Float(), nullable=True),
    sa.Column('negative_language_introduction', sa.Float(), nullable=True),
    sa.Column('negative_language_removal', sa.Float(), nullable=True),
    sa.Column('positive_language_introduction', sa.Float(), nullable=True),
    sa.Column('positive_language_removal', sa.Float(), nullable=True),
    sa.Column('risk_language_introduction', sa.Float(), nullable=True),
    sa.Column('risk_language_removal', sa.Float(), nullable=True),
    sa.Column('forward_looking_caution_change', sa.Float(), nullable=True),
    sa.Column('governance_language_change', sa.Float(), nullable=True),
    sa.Column('financial_condition_language_change', sa.Float(), nullable=True),
    sa.Column('risk_rate_earlier', sa.Float(), nullable=True),
    sa.Column('risk_rate_later', sa.Float(), nullable=True),
    sa.Column('financial_condition_rate_earlier', sa.Float(), nullable=True),
    sa.Column('financial_condition_rate_later', sa.Float(), nullable=True),
    sa.Column('governance_rate_earlier', sa.Float(), nullable=True),
    sa.Column('governance_rate_later', sa.Float(), nullable=True),
    sa.Column('strategy_rate_earlier', sa.Float(), nullable=True),
    sa.Column('strategy_rate_later', sa.Float(), nullable=True),
    sa.Column('analyzed_word_coverage', sa.Float(), nullable=True),
    sa.Column('primary_narrative_coverage', sa.Float(), nullable=True),
    sa.Column('dictionary_match_rate', sa.Float(), nullable=True),
    sa.Column('list_content_share', sa.Float(), nullable=True),
    sa.Column('uncertain_content_share', sa.Float(), nullable=True),
    sa.Column('ambiguous_alignment_share', sa.Float(), nullable=True),
    sa.Column('low_confidence_share', sa.Float(), nullable=True),
    sa.Column('language_signal_quality', sa.Enum('GOOD', 'USABLE', 'NEEDS_REVIEW', 'FAILED', name='language_signal_quality'), nullable=False),
    sa.Column('primary_eligible', sa.Boolean(), nullable=False),
    sa.Column('warning_reasons', sa.Text(), nullable=True),
    sa.Column('exclusion_reasons', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earlier_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_signal_run_id'], ['language_signal_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['later_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_pair_id'], ['report_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_signal_run_id')
    )
    op.create_index('ix_report_pair_language_features_primary_eligible', 'report_pair_language_features', ['primary_eligible'], unique=False)
    op.create_index('ix_report_pair_language_features_quality', 'report_pair_language_features', ['language_signal_quality'], unique=False)
    op.create_index('ix_report_pair_language_features_report_pair_id', 'report_pair_language_features', ['report_pair_id'], unique=False)
    op.create_table('passage_language_category_hits',
    sa.Column('passage_language_signal_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('negated_hit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['passage_language_signal_id'], ['passage_language_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passage_language_signal_id', 'category', 'subcategory', name='uq_passage_language_category_hits_signal_category')
    )
    op.create_index('ix_passage_language_category_hits_signal_id', 'passage_language_category_hits', ['passage_language_signal_id'], unique=False)
    # ### end Alembic commands ###
    # Note: autogenerate also proposed dropping 'ix_passage_embeddings_embedding_
    # hnsw_cosine' here -- a false positive (SQLAlchemy's reflection can't fully
    # match a raw-SQL pgvector HNSW index against the ORM declaration from
    # 2ee4738d0d76_passage_embedding_hnsw_index.py); deliberately not applied,
    # since it is unrelated to this revision and would drop a real M4 index.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_passage_language_category_hits_signal_id', table_name='passage_language_category_hits')
    op.drop_table('passage_language_category_hits')
    op.drop_index('ix_report_pair_language_features_report_pair_id', table_name='report_pair_language_features')
    op.drop_index('ix_report_pair_language_features_quality', table_name='report_pair_language_features')
    op.drop_index('ix_report_pair_language_features_primary_eligible', table_name='report_pair_language_features')
    op.drop_table('report_pair_language_features')
    op.drop_index('ix_passage_language_signals_run_id', table_name='passage_language_signals')
    op.drop_index('ix_passage_language_signals_passage_id', table_name='passage_language_signals')
    op.drop_index('ix_passage_language_signals_alignment_status', table_name='passage_language_signals')
    op.drop_table('passage_language_signals')
    op.drop_index('ix_language_signal_runs_pair_status', table_name='language_signal_runs')
    op.drop_index('ix_language_signal_runs_pair_completed_at', table_name='language_signal_runs')
    op.drop_table('language_signal_runs')
    op.drop_index('ix_financial_language_terms_normalized_term', table_name='financial_language_terms')
    op.drop_index('ix_financial_language_terms_dictionary_id', table_name='financial_language_terms')
    op.drop_index('ix_financial_language_terms_category', table_name='financial_language_terms')
    op.drop_table('financial_language_terms')
    op.drop_table('financial_language_dictionaries')
    # ### end Alembic commands ###
    # Enum types created by this revision only -- 'alignment_status',
    # 'alignment_confidence', and 'passage_type' are reused from earlier
    # revisions and must not be dropped here.
    sa.Enum(name='language_signal_run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='language_signal_quality').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='report_side').drop(op.get_bind(), checkfirst=True)
