"""disclosure change features

Revision ID: 2caf70d7f084
Revises: ba39585395d7
Create Date: 2026-07-17 12:32:13.659699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2caf70d7f084'
down_revision: Union[str, Sequence[str], None] = 'ba39585395d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_runs',
    sa.Column('report_pair_id', sa.UUID(), nullable=False),
    sa.Column('similarity_run_id', sa.UUID(), nullable=False),
    sa.Column('alignment_run_id', sa.UUID(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=64), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='feature_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alignment_run_id'], ['alignment_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_pair_id'], ['report_pairs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similarity_run_id'], ['similarity_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_runs_pair_completed_at', 'feature_runs', ['report_pair_id', 'completed_at'], unique=False)
    op.create_index('ix_feature_runs_pair_status', 'feature_runs', ['report_pair_id', 'status'], unique=False)
    op.create_table('report_pair_features',
    sa.Column('feature_run_id', sa.UUID(), nullable=False),
    sa.Column('report_pair_id', sa.UUID(), nullable=False),
    sa.Column('earlier_report_id', sa.UUID(), nullable=False),
    sa.Column('later_report_id', sa.UUID(), nullable=False),
    sa.Column('document_cosine_similarity', sa.Float(), nullable=True),
    sa.Column('document_bigram_jaccard', sa.Float(), nullable=True),
    sa.Column('document_edit_similarity', sa.Float(), nullable=True),
    sa.Column('document_diff_similarity', sa.Float(), nullable=True),
    sa.Column('document_word_change_ratio', sa.Float(), nullable=True),
    sa.Column('document_metric_disagreement_spread', sa.Float(), nullable=True),
    sa.Column('document_quality', postgresql.ENUM('GOOD', 'USABLE', 'NEEDS_REVIEW', 'FAILED', name='similarity_result_quality', create_type=False), nullable=True),
    sa.Column('document_primary_eligible', sa.Boolean(), nullable=True),
    sa.Column('document_cosine_change', sa.Float(), nullable=True),
    sa.Column('document_bigram_jaccard_change', sa.Float(), nullable=True),
    sa.Column('document_edit_similarity_change', sa.Float(), nullable=True),
    sa.Column('document_diff_similarity_change', sa.Float(), nullable=True),
    sa.Column('document_word_change_ratio_abs', sa.Float(), nullable=True),
    sa.Column('earlier_passage_count', sa.Integer(), nullable=False),
    sa.Column('later_passage_count', sa.Integer(), nullable=False),
    sa.Column('aligned_passage_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_count', sa.Integer(), nullable=False),
    sa.Column('lightly_modified_count', sa.Integer(), nullable=False),
    sa.Column('substantially_modified_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('removed_count', sa.Integer(), nullable=False),
    sa.Column('ambiguous_count', sa.Integer(), nullable=False),
    sa.Column('high_confidence_count', sa.Integer(), nullable=False),
    sa.Column('medium_confidence_count', sa.Integer(), nullable=False),
    sa.Column('low_confidence_count', sa.Integer(), nullable=False),
    sa.Column('needs_review_confidence_count', sa.Integer(), nullable=False),
    sa.Column('skipped_embedding_count_earlier', sa.Integer(), nullable=False),
    sa.Column('skipped_embedding_count_later', sa.Integer(), nullable=False),
    sa.Column('earlier_word_count', sa.Integer(), nullable=False),
    sa.Column('later_word_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_words', sa.Float(), nullable=False),
    sa.Column('lightly_modified_words', sa.Float(), nullable=False),
    sa.Column('substantially_modified_words', sa.Float(), nullable=False),
    sa.Column('new_words', sa.Float(), nullable=False),
    sa.Column('removed_words', sa.Float(), nullable=False),
    sa.Column('ambiguous_words', sa.Float(), nullable=False),
    sa.Column('eligible_earlier_passage_count', sa.Integer(), nullable=False),
    sa.Column('eligible_later_passage_count', sa.Integer(), nullable=False),
    sa.Column('eligible_aligned_passage_count', sa.Integer(), nullable=False),
    sa.Column('eligible_unchanged_count', sa.Integer(), nullable=False),
    sa.Column('eligible_lightly_modified_count', sa.Integer(), nullable=False),
    sa.Column('eligible_substantially_modified_count', sa.Integer(), nullable=False),
    sa.Column('eligible_new_count', sa.Integer(), nullable=False),
    sa.Column('eligible_removed_count', sa.Integer(), nullable=False),
    sa.Column('eligible_ambiguous_count', sa.Integer(), nullable=False),
    sa.Column('eligible_unchanged_words', sa.Float(), nullable=False),
    sa.Column('eligible_lightly_modified_words', sa.Float(), nullable=False),
    sa.Column('eligible_substantially_modified_words', sa.Float(), nullable=False),
    sa.Column('eligible_new_words', sa.Float(), nullable=False),
    sa.Column('eligible_removed_words', sa.Float(), nullable=False),
    sa.Column('eligible_ambiguous_words', sa.Float(), nullable=False),
    sa.Column('excluded_low_information_count', sa.Integer(), nullable=False),
    sa.Column('excluded_low_information_words', sa.Float(), nullable=False),
    sa.Column('excluded_heading_fragment_count', sa.Integer(), nullable=False),
    sa.Column('excluded_heading_fragment_words', sa.Float(), nullable=False),
    sa.Column('heading_fragment_share_earlier', sa.Float(), nullable=True),
    sa.Column('heading_fragment_share_later', sa.Float(), nullable=True),
    sa.Column('unchanged_rate_count', sa.Float(), nullable=True),
    sa.Column('lightly_modified_rate_count', sa.Float(), nullable=True),
    sa.Column('substantially_modified_rate_count', sa.Float(), nullable=True),
    sa.Column('new_rate_count', sa.Float(), nullable=True),
    sa.Column('removed_rate_count', sa.Float(), nullable=True),
    sa.Column('ambiguous_rate_count', sa.Float(), nullable=True),
    sa.Column('unchanged_rate_words', sa.Float(), nullable=True),
    sa.Column('lightly_modified_rate_words', sa.Float(), nullable=True),
    sa.Column('substantially_modified_rate_words', sa.Float(), nullable=True),
    sa.Column('new_rate_words', sa.Float(), nullable=True),
    sa.Column('removed_rate_words', sa.Float(), nullable=True),
    sa.Column('ambiguous_rate_words', sa.Float(), nullable=True),
    sa.Column('alignment_coverage_count', sa.Float(), nullable=True),
    sa.Column('alignment_coverage_words', sa.Float(), nullable=True),
    sa.Column('embedded_coverage_earlier', sa.Float(), nullable=True),
    sa.Column('embedded_coverage_later', sa.Float(), nullable=True),
    sa.Column('high_confidence_share', sa.Float(), nullable=True),
    sa.Column('review_required_share', sa.Float(), nullable=True),
    sa.Column('irregular_gap', sa.Boolean(), nullable=False),
    sa.Column('reporting_gap_months', sa.Integer(), nullable=False),
    sa.Column('transition_report', sa.Boolean(), nullable=False),
    sa.Column('feature_quality', sa.Enum('GOOD', 'USABLE', 'NEEDS_REVIEW', 'FAILED', name='feature_quality'), nullable=False),
    sa.Column('primary_eligible', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reasons', sa.Text(), nullable=True),
    sa.Column('warning_reasons', sa.Text(), nullable=True),
    sa.Column('disclosure_change_score', sa.Float(), nullable=True),
    sa.Column('score_version', sa.String(length=64), nullable=False),
    sa.Column('score_unchanged_component', sa.Float(), nullable=True),
    sa.Column('score_lightly_modified_component', sa.Float(), nullable=True),
    sa.Column('score_substantially_modified_component', sa.Float(), nullable=True),
    sa.Column('score_new_component', sa.Float(), nullable=True),
    sa.Column('score_removed_component', sa.Float(), nullable=True),
    sa.Column('score_ambiguous_component', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earlier_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_run_id'], ['feature_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['later_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_pair_id'], ['report_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_run_id')
    )
    op.create_index('ix_report_pair_features_primary_eligible', 'report_pair_features', ['primary_eligible'], unique=False)
    op.create_index('ix_report_pair_features_quality', 'report_pair_features', ['feature_quality'], unique=False)
    op.create_index('ix_report_pair_features_report_pair_id', 'report_pair_features', ['report_pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_pair_features_report_pair_id', table_name='report_pair_features')
    op.drop_index('ix_report_pair_features_quality', table_name='report_pair_features')
    op.drop_index('ix_report_pair_features_primary_eligible', table_name='report_pair_features')
    op.drop_table('report_pair_features')
    op.drop_index('ix_feature_runs_pair_status', table_name='feature_runs')
    op.drop_index('ix_feature_runs_pair_completed_at', table_name='feature_runs')
    op.drop_table('feature_runs')
    # ### end Alembic commands ###
    # Enum types created by this revision only -- 'similarity_result_quality'
    # is reused from an earlier revision and must not be dropped here.
    sa.Enum(name='feature_quality').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='feature_run_status').drop(op.get_bind(), checkfirst=True)
