"""initial schema

Revision ID: 2ff2ba0b15e2
Revises: 
Create Date: 2026-07-15 13:59:43.295633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff2ba0b15e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('reports',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_bytes', sa.Integer(), nullable=True),
    sa.Column('directory_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_label', sa.String(length=64), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('reporting_months', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('metadata_status', sa.Enum('DISCOVERED', 'INSPECTED', 'VALIDATED', 'NEEDS_REVIEW', 'REJECTED', name='metadata_status'), nullable=False),
    sa.Column('metadata_source', sa.Enum('DIRECTORY', 'FILENAME', 'PDF', 'MANUAL', name='metadata_source'), nullable=False),
    sa.Column('transition_report', sa.Boolean(), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_path'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index('uq_reports_company_period_end', 'reports', ['company_id', 'period_end'], unique=True, postgresql_where=sa.text('period_end IS NOT NULL'))
    op.create_table('report_pairs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('earlier_report_id', sa.UUID(), nullable=False),
    sa.Column('later_report_id', sa.UUID(), nullable=False),
    sa.Column('gap_months', sa.Integer(), nullable=False),
    sa.Column('is_transition', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['earlier_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['later_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('earlier_report_id', 'later_report_id', name='uq_report_pairs_earlier_later')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_pairs')
    op.drop_index('uq_reports_company_period_end', table_name='reports', postgresql_where=sa.text('period_end IS NOT NULL'))
    op.drop_table('reports')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
    sa.Enum(name='metadata_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='metadata_source').drop(op.get_bind(), checkfirst=True)
    op.execute("DROP EXTENSION IF EXISTS vector")
