"""extraction pipeline

Revision ID: 8c622d3ced32
Revises: 2ff2ba0b15e2
Create Date: 2026-07-15 15:24:46.591127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c622d3ced32'
down_revision: Union[str, Sequence[str], None] = '2ff2ba0b15e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_runs',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('extractor_name', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='extraction_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('expected_page_count', sa.Integer(), nullable=True),
    sa.Column('processed_page_count', sa.Integer(), nullable=True),
    sa.Column('usable_page_count', sa.Integer(), nullable=True),
    sa.Column('low_text_page_count', sa.Integer(), nullable=True),
    sa.Column('image_only_page_count', sa.Integer(), nullable=True),
    sa.Column('total_word_count', sa.Integer(), nullable=True),
    sa.Column('extraction_quality', sa.Enum('GOOD', 'USABLE', 'NEEDS_REVIEW', 'FAILED', name='extraction_quality'), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('encrypted_pdf_handled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extraction_runs_report_completed_at', 'extraction_runs', ['report_id', 'completed_at'], unique=False)
    op.create_index('ix_extraction_runs_report_status', 'extraction_runs', ['report_id', 'status'], unique=False)
    op.create_table('narrative_documents',
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_run_id')
    )
    op.create_index('ix_narrative_documents_report_id', 'narrative_documents', ['report_id'], unique=False)
    op.create_table('pages',
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('native_text_available', sa.Boolean(), nullable=False),
    sa.Column('suspected_image_only', sa.Boolean(), nullable=False),
    sa.Column('extraction_quality', sa.Enum('GOOD', 'USABLE', 'NEEDS_REVIEW', 'FAILED', name='extraction_quality'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_run_id', 'page_number', name='uq_pages_run_page_number')
    )
    op.create_index('ix_pages_report_page_number', 'pages', ['report_id', 'page_number'], unique=False)
    op.create_table('text_blocks',
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('block_type', sa.Enum('PARAGRAPH', 'HEADING_CANDIDATE', 'LIST_ITEM', 'TABLE_LIKE', 'HEADER', 'FOOTER', 'PAGE_NUMBER', 'NUMERIC_FRAGMENT', 'DECORATIVE_OR_FRAGMENT', 'UNKNOWN', name='block_type'), nullable=False),
    sa.Column('x0', sa.Float(), nullable=True),
    sa.Column('y0', sa.Float(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('font_size', sa.Float(), nullable=True),
    sa.Column('is_bold', sa.Boolean(), nullable=True),
    sa.Column('is_repeated_header', sa.Boolean(), nullable=False),
    sa.Column('is_repeated_footer', sa.Boolean(), nullable=False),
    sa.Column('excluded_from_narrative', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_run_id', 'page_id', 'block_index', name='uq_text_blocks_run_page_block_index')
    )
    op.create_index('ix_text_blocks_page_reading_order', 'text_blocks', ['page_id', 'reading_order'], unique=False)
    op.create_index('ix_text_blocks_report_id', 'text_blocks', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_text_blocks_report_id', table_name='text_blocks')
    op.drop_index('ix_text_blocks_page_reading_order', table_name='text_blocks')
    op.drop_table('text_blocks')
    op.drop_index('ix_pages_report_page_number', table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_narrative_documents_report_id', table_name='narrative_documents')
    op.drop_table('narrative_documents')
    op.drop_index('ix_extraction_runs_report_status', table_name='extraction_runs')
    op.drop_index('ix_extraction_runs_report_completed_at', table_name='extraction_runs')
    op.drop_table('extraction_runs')
    # ### end Alembic commands ###
    sa.Enum(name='block_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='extraction_quality').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='extraction_status').drop(op.get_bind(), checkfirst=True)
