"""passage segmentation, embedding, and alignment

Revision ID: ba39585395d7
Revises: c9e96ef451f1
Create Date: 2026-07-16 12:31:24.290183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'ba39585395d7'
down_revision: Union[str, Sequence[str], None] = 'c9e96ef451f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passage_segmentation_runs',
    sa.Column('narrative_document_id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='passage_segmentation_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('passage_count', sa.Integer(), nullable=True),
    sa.Column('excluded_passage_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['narrative_document_id'], ['narrative_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_passage_segmentation_runs_narrative_doc_completed_at', 'passage_segmentation_runs', ['narrative_document_id', 'completed_at'], unique=False)
    op.create_index('ix_passage_segmentation_runs_narrative_doc_status', 'passage_segmentation_runs', ['narrative_document_id', 'status'], unique=False)
    op.create_table('embedding_runs',
    sa.Column('segmentation_run_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_revision', sa.String(length=64), nullable=False),
    sa.Column('tokenizer_name', sa.String(length=255), nullable=False),
    sa.Column('tokenizer_revision', sa.String(length=64), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('pooling_strategy', sa.String(length=32), nullable=False),
    sa.Column('normalization_method', sa.String(length=32), nullable=False),
    sa.Column('maximum_model_tokens', sa.Integer(), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='embedding_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('embedded_passage_count', sa.Integer(), nullable=True),
    sa.Column('skipped_passage_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segmentation_run_id'], ['passage_segmentation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_embedding_runs_segmentation_run_completed_at', 'embedding_runs', ['segmentation_run_id', 'completed_at'], unique=False)
    op.create_index('ix_embedding_runs_segmentation_run_status', 'embedding_runs', ['segmentation_run_id', 'status'], unique=False)
    op.create_table('passages',
    sa.Column('segmentation_run_id', sa.UUID(), nullable=False),
    sa.Column('narrative_document_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('passage_index', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('first_page_number', sa.Integer(), nullable=False),
    sa.Column('last_page_number', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('heading_text', sa.Text(), nullable=True),
    sa.Column('passage_type', sa.Enum('HEADING_WITH_BODY', 'PARAGRAPH', 'MULTI_PARAGRAPH', 'LIST', 'TABLE_CONTEXT', 'OTHER', name='passage_type'), nullable=False),
    sa.Column('excluded_from_alignment', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['narrative_document_id'], ['narrative_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segmentation_run_id'], ['passage_segmentation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segmentation_run_id', 'passage_index', name='uq_passages_run_passage_index')
    )
    op.create_index('ix_passages_narrative_document_id', 'passages', ['narrative_document_id'], unique=False)
    op.create_index('ix_passages_report_id', 'passages', ['report_id'], unique=False)
    op.create_index('ix_passages_segmentation_run_excluded', 'passages', ['segmentation_run_id', 'excluded_from_alignment'], unique=False)
    op.create_table('alignment_runs',
    sa.Column('report_pair_id', sa.UUID(), nullable=False),
    sa.Column('earlier_segmentation_run_id', sa.UUID(), nullable=False),
    sa.Column('later_segmentation_run_id', sa.UUID(), nullable=False),
    sa.Column('earlier_embedding_run_id', sa.UUID(), nullable=False),
    sa.Column('later_embedding_run_id', sa.UUID(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='alignment_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=True),
    sa.Column('unchanged_count', sa.Integer(), nullable=True),
    sa.Column('lightly_modified_count', sa.Integer(), nullable=True),
    sa.Column('substantially_modified_count', sa.Integer(), nullable=True),
    sa.Column('new_count', sa.Integer(), nullable=True),
    sa.Column('removed_count', sa.Integer(), nullable=True),
    sa.Column('ambiguous_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earlier_embedding_run_id'], ['embedding_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['earlier_segmentation_run_id'], ['passage_segmentation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['later_embedding_run_id'], ['embedding_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['later_segmentation_run_id'], ['passage_segmentation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_pair_id'], ['report_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alignment_runs_pair_completed_at', 'alignment_runs', ['report_pair_id', 'completed_at'], unique=False)
    op.create_index('ix_alignment_runs_pair_status', 'alignment_runs', ['report_pair_id', 'status'], unique=False)
    op.create_table('passage_embeddings',
    sa.Column('embedding_run_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('input_token_count', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['embedding_run_id'], ['embedding_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embedding_run_id', 'passage_id', name='uq_passage_embeddings_run_passage')
    )
    op.create_index('ix_passage_embeddings_passage_id', 'passage_embeddings', ['passage_id'], unique=False)
    op.create_table('passage_source_blocks',
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('text_block_id', sa.UUID(), nullable=False),
    sa.Column('segmentation_run_id', sa.UUID(), nullable=False),
    sa.Column('source_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segmentation_run_id'], ['passage_segmentation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_block_id'], ['text_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passage_id', 'source_order', name='uq_passage_source_blocks_passage_order'),
    sa.UniqueConstraint('segmentation_run_id', 'text_block_id', name='uq_passage_source_blocks_run_text_block')
    )
    op.create_index('ix_passage_source_blocks_passage_id', 'passage_source_blocks', ['passage_id'], unique=False)
    op.create_index('ix_passage_source_blocks_text_block_id', 'passage_source_blocks', ['text_block_id'], unique=False)
    op.create_table('passage_alignments',
    sa.Column('alignment_run_id', sa.UUID(), nullable=False),
    sa.Column('report_pair_id', sa.UUID(), nullable=False),
    sa.Column('earlier_passage_id', sa.UUID(), nullable=True),
    sa.Column('later_passage_id', sa.UUID(), nullable=True),
    sa.Column('alignment_status', sa.Enum('UNCHANGED', 'LIGHTLY_MODIFIED', 'SUBSTANTIALLY_MODIFIED', 'NEW', 'REMOVED', 'AMBIGUOUS', name='alignment_status'), nullable=False),
    sa.Column('alignment_type', sa.Enum('ONE_TO_ONE', 'ONE_TO_TWO', 'TWO_TO_ONE', 'UNMATCHED_EARLIER', 'UNMATCHED_LATER', name='alignment_type'), nullable=False),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('lexical_cosine_similarity', sa.Float(), nullable=True),
    sa.Column('jaccard_similarity', sa.Float(), nullable=True),
    sa.Column('edit_similarity', sa.Float(), nullable=True),
    sa.Column('heading_similarity', sa.Float(), nullable=True),
    sa.Column('length_ratio', sa.Float(), nullable=True),
    sa.Column('position_difference', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('candidate_rank', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NEEDS_REVIEW', name='alignment_confidence'), nullable=False),
    sa.Column('best_second_margin', sa.Float(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('primary_alignment', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alignment_run_id'], ['alignment_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['earlier_passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['later_passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_pair_id'], ['report_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_passage_alignments_confidence', 'passage_alignments', ['alignment_run_id', 'confidence'], unique=False)
    op.create_index('ix_passage_alignments_report_pair_id', 'passage_alignments', ['report_pair_id'], unique=False)
    op.create_index('ix_passage_alignments_run_id', 'passage_alignments', ['alignment_run_id'], unique=False)
    op.create_index('ix_passage_alignments_status', 'passage_alignments', ['alignment_run_id', 'alignment_status'], unique=False)
    op.create_index('uq_passage_alignments_run_earlier_primary', 'passage_alignments', ['alignment_run_id', 'earlier_passage_id'], unique=True, postgresql_where=sa.text('earlier_passage_id IS NOT NULL AND primary_alignment'))
    op.create_index('uq_passage_alignments_run_later_primary', 'passage_alignments', ['alignment_run_id', 'later_passage_id'], unique=True, postgresql_where=sa.text('later_passage_id IS NOT NULL AND primary_alignment'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_passage_alignments_run_later_primary', table_name='passage_alignments', postgresql_where=sa.text('later_passage_id IS NOT NULL AND primary_alignment'))
    op.drop_index('uq_passage_alignments_run_earlier_primary', table_name='passage_alignments', postgresql_where=sa.text('earlier_passage_id IS NOT NULL AND primary_alignment'))
    op.drop_index('ix_passage_alignments_status', table_name='passage_alignments')
    op.drop_index('ix_passage_alignments_run_id', table_name='passage_alignments')
    op.drop_index('ix_passage_alignments_report_pair_id', table_name='passage_alignments')
    op.drop_index('ix_passage_alignments_confidence', table_name='passage_alignments')
    op.drop_table('passage_alignments')
    op.drop_index('ix_passage_source_blocks_text_block_id', table_name='passage_source_blocks')
    op.drop_index('ix_passage_source_blocks_passage_id', table_name='passage_source_blocks')
    op.drop_table('passage_source_blocks')
    op.drop_index('ix_passage_embeddings_passage_id', table_name='passage_embeddings')
    op.drop_table('passage_embeddings')
    op.drop_index('ix_alignment_runs_pair_status', table_name='alignment_runs')
    op.drop_index('ix_alignment_runs_pair_completed_at', table_name='alignment_runs')
    op.drop_table('alignment_runs')
    op.drop_index('ix_passages_segmentation_run_excluded', table_name='passages')
    op.drop_index('ix_passages_report_id', table_name='passages')
    op.drop_index('ix_passages_narrative_document_id', table_name='passages')
    op.drop_table('passages')
    op.drop_index('ix_embedding_runs_segmentation_run_status', table_name='embedding_runs')
    op.drop_index('ix_embedding_runs_segmentation_run_completed_at', table_name='embedding_runs')
    op.drop_table('embedding_runs')
    op.drop_index('ix_passage_segmentation_runs_narrative_doc_status', table_name='passage_segmentation_runs')
    op.drop_index('ix_passage_segmentation_runs_narrative_doc_completed_at', table_name='passage_segmentation_runs')
    op.drop_table('passage_segmentation_runs')
    # ### end Alembic commands ###
    sa.Enum(name='alignment_confidence').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='alignment_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='alignment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='alignment_run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='passage_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='embedding_run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='passage_segmentation_run_status').drop(op.get_bind(), checkfirst=True)
