"""diff mode and duration tracking

Revision ID: c9e96ef451f1
Revises: d8118d0f8412
Create Date: 2026-07-16 10:43:27.182879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e96ef451f1'
down_revision: Union[str, Sequence[str], None] = 'd8118d0f8412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Unlike the enums in prior migrations (created implicitly by
    # create_table), this one is added to an existing table via ADD COLUMN,
    # which does not create the Postgres type on its own -- it must be
    # created explicitly first.
    diff_mode_enum = sa.Enum('FULL_NO_AUTOJUNK', 'FULL_AUTOJUNK', 'SKIPPED_TOKEN_LIMIT', name='diff_mode')
    diff_mode_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('document_similarities', sa.Column('diff_mode', diff_mode_enum, nullable=True))
    op.add_column('document_similarities', sa.Column('diff_duration_ms', sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_similarities', 'diff_duration_ms')
    op.drop_column('document_similarities', 'diff_mode')
    # ### end Alembic commands ###
    sa.Enum(name='diff_mode').drop(op.get_bind(), checkfirst=True)
