"""similarity scoring

Revision ID: d8118d0f8412
Revises: 8c622d3ced32
Create Date: 2026-07-16 09:49:29.781976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8118d0f8412'
down_revision: Union[str, Sequence[str], None] = '8c622d3ced32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similarity_runs',
    sa.Column('report_pair_id', sa.UUID(), nullable=False),
    sa.Column('earlier_narrative_document_id', sa.UUID(), nullable=False),
    sa.Column('later_narrative_document_id', sa.UUID(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', name='similarity_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earlier_narrative_document_id'], ['narrative_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['later_narrative_document_id'], ['narrative_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_pair_id'], ['report_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_similarity_runs_pair_completed_at', 'similarity_runs', ['report_pair_id', 'completed_at'], unique=False)
    op.create_index('ix_similarity_runs_pair_status', 'similarity_runs', ['report_pair_id', 'status'], unique=False)
    op.create_table('document_similarities',
    sa.Column('similarity_run_id', sa.UUID(), nullable=False),
    sa.Column('report_pair_id', sa.UUID(), nullable=False),
    sa.Column('earlier_report_id', sa.UUID(), nullable=False),
    sa.Column('later_report_id', sa.UUID(), nullable=False),
    sa.Column('lexical_cosine_similarity', sa.Float(), nullable=True),
    sa.Column('jaccard_similarity', sa.Float(), nullable=True),
    sa.Column('diff_similarity', sa.Float(), nullable=True),
    sa.Column('edit_similarity', sa.Float(), nullable=True),
    sa.Column('earlier_word_count', sa.Integer(), nullable=False),
    sa.Column('later_word_count', sa.Integer(), nullable=False),
    sa.Column('word_count_change', sa.Integer(), nullable=False),
    sa.Column('word_count_change_ratio', sa.Float(), nullable=True),
    sa.Column('earlier_character_count', sa.Integer(), nullable=False),
    sa.Column('later_character_count', sa.Integer(), nullable=False),
    sa.Column('character_count_change', sa.Integer(), nullable=False),
    sa.Column('character_count_change_ratio', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.Enum('GOOD', 'USABLE', 'NEEDS_REVIEW', 'FAILED', name='similarity_result_quality'), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('primary_analysis_eligible', sa.Boolean(), nullable=False),
    sa.Column('primary_analysis_exclusion_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['earlier_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['later_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_pair_id'], ['report_pairs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similarity_run_id'], ['similarity_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('similarity_run_id')
    )
    op.create_index('ix_document_similarities_earlier_report_id', 'document_similarities', ['earlier_report_id'], unique=False)
    op.create_index('ix_document_similarities_later_report_id', 'document_similarities', ['later_report_id'], unique=False)
    op.create_index('ix_document_similarities_report_pair_id', 'document_similarities', ['report_pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_similarities_report_pair_id', table_name='document_similarities')
    op.drop_index('ix_document_similarities_later_report_id', table_name='document_similarities')
    op.drop_index('ix_document_similarities_earlier_report_id', table_name='document_similarities')
    op.drop_table('document_similarities')
    op.drop_index('ix_similarity_runs_pair_status', table_name='similarity_runs')
    op.drop_index('ix_similarity_runs_pair_completed_at', table_name='similarity_runs')
    op.drop_table('similarity_runs')
    # ### end Alembic commands ###
    sa.Enum(name='similarity_result_quality').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='similarity_run_status').drop(op.get_bind(), checkfirst=True)
